### ISSUE TITLE
Need to have more customizable options

### ISSUE THREAD

**Issue by thewebkid** [Innologica/vue2-daterange-picker#1]
Wondering what your plan is to make this a fully customizable vue component. I am somewhat new to vue, but I think all I need to use this in my project is to be able to pass props for some of the locale opts you have hardcoded into lines 85-95 of the dataRangePicker.vue. I could take a stab at this for you via a pull request if you like. Otherwise, please let me know when you plan to finish this up. I don't care about the docs as much as the flexiblility. I can wait a couple of months before I need to put localized strings, custom options, etc., into my implementation.

Thanks for putting this on npm! Great wrap job!

Ron

**Comment by nkostadinov** [comment]
Hi @thewebkid ,
thanks for the feedback. I've added localeData props to the component and bumped the version number so now you canoverride any of the locales that the component uses. 
I'm in a hurry to finish a big project so I wont finish the component in the next month or two, but if you have any issues I will fix them :) 

These are the default options:
```
{
        direction: 'ltr',
        format: moment.localeData().longDateFormat('L'),
        separator: ' - ',
        applyLabel: 'Apply',
        cancelLabel: 'Cancel',
        weekLabel: 'W',
        customRangeLabel: 'Custom Range',
        daysOfWeek: moment.weekdaysMin(),
        monthNames: moment.monthsShort(),
        firstDay: moment.localeData().firstDayOfWeek()
      }
```

You could override any of these via the locale-data prop like this(e.g. update days of week) : 
```
            <date-range-picker
                    :opens="opens"
                    :startDate="startDate"
                    :endDate="endDate"
                    :locale-data="{ daysOfWeek: [ 'Нд', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб' ] }"
            ></date-range-picker>
```

**Comment by thewebkid** [comment]
Thanks, I will try it out again in a few days. I ended up using the plugin as a hacked solution for now, but will let you know how it goes when I implement it. I couldn't get it to run at all when I first tried it. Hopefully I have better luck...
