### ISSUE TITLE
Mobile view

### ISSUE THREAD

**Issue by mmusket** [Innologica/vue2-daterange-picker#100]
Positioning the control in a mobile environment is clunky. Can we have an option where it foes full screen? (With some optional margin?)

**Comment by nkostadinov** [comment]
I think we can have such an option but it I think I will make it with bootstrap classes.

**Comment by mmusket** [comment]
sounds good

**Comment by nkostadinov** [comment]
the only downside is that it will add bootstrap as a dependency in order to have mobile friendly component.

**Comment by mmusket** [comment]
that is less ideal. The bootstrap class essentially checks that the window size is less than 700px maybe you can just mimick that ?

**Comment by madroneropaulo** [comment]
Any news on this?

**Comment by MenaiAla** [comment]
I'm trying to add tailwind CSS `flex flex-col` ( equal to display: block) but I don't know how I can override the div :

**css :** 

```
.daterangepicker {
  background-color: red;
  @apply flex flex-col;
}
```
**Result :** 

![Screenshot_3](https://user-images.githubusercontent.com/20143684/79704067-55708780-8264-11ea-9b5e-d707fffd338c.png)

I want to display the calendar vertically, But I don't understand which class I access.

**Comment by jlanzarotti** [comment]
Give this a try

`
.daterangepicker .calendars-container {
  display: flex;
  flex-wrap: wrap;
}
.drp-calendar .col .left {
  flex: 0 0 auto;
}
`

**Comment by nkostadinov** [comment]
new version aligns them vertically so it is kind of responseive
