### ISSUE TITLE
Firefox and Chrome are behaving differently...

### ISSUE THREAD

**Issue by Dadsaster** [Innologica/vue2-daterange-picker#104]
I'm testing with:

FireFox 70.0.1 (64-bit)
Chrome Version 78.0.3904.97 (64-bit)

Here is what my implementation looks like:

`<date-range-picker
                        :startDate="startDate"
                        :endDate="endDate"
                        class="ml-2"
                        @update="dateChanged"
                        :locale-data="locale">
                    <div slot="input" slot-scope="picker">{{picker.startDate|formatCalendarDate}} - {{picker.endDate|formatCalendarDate}}<fa class="ml-4" icon="calendar-alt"/></div>
                </date-range-picker>`

With data:

`startDate: moment().format('MM-DD-YYYY'),
  endDate: moment().format('MM-DD-YYYY'),
  locale: {
                direction: 'ltr',
                format: 'MM-DD-YYYY',
                separator: ' - ',
                applyLabel: 'Apply',
                cancelLabel: 'Cancel',
                weekLabel: 'W',
                customRangeLabel: 'Custom Range',
                daysOfWeek: moment.weekdaysMin(),
                monthNames: moment.monthsShort(),
                firstDay: 1
 }`

And the filter:

`filters: {
        formatCalendarDate (date) {
            return moment(date).format('MM/DD/YYYY');
        }
}`

In Chrome - everything works as expected
In FireFox - Invalid Date

**Comment by nirmal93guna** [comment]
It happens for me in Safari, whereas Chrome and Firefox works just fine.

**Comment by Dadsaster** [comment]
After some more digging - for some reason Moment behaves differently in Firefox and Chrome.  Changing format to (MM/DD/YYYY) everywhere go firefox working again.  I'm going to close this as the issue seems to be with momentjs.

**Comment by nkostadinov** [comment]
I'm preparing a new version where I implemented all date functions with native date object. So this should be handled properly I guess.
