### ISSUE TITLE
Add prop for single daterange picker.

### ISSUE THREAD

**Issue by chehonte** [Innologica/vue2-daterange-picker#106]
Hi!

Can you please add a prop for picker, that can enable range picker in single calendar. Now range picker works only with two calendar pickers and if we set single-date-picker, range picker is off. 

Thank you!

**Comment by chehonte** [comment]
Also clickRange method of DateRangePicker don't check **value** if they will be null.

**Comment by nkostadinov** [comment]
@chehonte it now checks if the value from range select. And I will add possibility to have single range picker with range select :)

**Comment by chehonte** [comment]
@nkostadinov Great news) Thank you for your job!

**Comment by jamesgraham** [comment]
@nkostadinov did you have time to think about the implementation for single picker/range select mode?

**Comment by nkostadinov** [comment]
already done
