### ISSUE TITLE
Integrate vue2-daterange-picker using CDN

### ISSUE THREAD

**Issue by jsnjiv** [Innologica/vue2-daterange-picker#107]
Hi,

I have tried to integrate this plugin using CDN but couldn't found any solutions. Please suggest how to achieve this.

**Comment by berkaygure** [comment]
Hi, 
Did you find any solution?

**Comment by berkaygure** [comment]
Hi again,
I have found a solution. You can do it with follow these steps.

1. Clone repo
2. Run `npm install && npm run lib` in repo.
3. Go to dist folder and copy `vue2-daterange-picker.umd.min.js`, `vue2-daterange-picker.css` files to your project.
4.  Import files with the script tags.
5. Register component to vue like this `Vue.component('vue2-daterange-picker', window['vue2-daterange-picker'].default);`

And you can start to use it.

**Comment by nkostadinov** [comment]
You can use: 
https://cdn.jsdelivr.net/npm/vue2-daterange-picker/
or
https://cdn.jsdelivr.net/npm/vue2-daterange-picker/

**Comment by markhorsman** [comment]
Hi,

I tried the steps from berkaygure but nothing is displayed in my component.
DateRangePicker is undefined.
I'm also using the cdn files.

`window.Vue.component('vue2-daterange-picker', window['vue2-daterange-picker'].default);

new window.Vue({
	el: '#dashboard-vue',
	components: {
		Quasar,
		Dashboard: window.httpVueLoader('/components/Dashboard.vue')
	},
	mounted() {}
});`

Any help would be greatly appreciated.

**Comment by berkaygure** [comment]
Hi, 
You should import CSS file and set a dateRange as v-model.

<img width="918" alt="Screen Shot 2020-04-15 at 22 15 44" src="https://user-images.githubusercontent.com/5683957/79378895-c3683680-7f66-11ea-8b4d-2920e55a93b0.png">

It works for me.
https://codepen.io/berkaygure/pen/ZEbQaEX
