### ISSUE TITLE
Module parse failed: Unexpected token (114:26)

### ISSUE THREAD

**Issue by erhansaydam** [Innologica/vue2-daterange-picker#11]
Hi,

After npm install and run, it returns a "Module parse failed" error.

Module parse failed: Unexpected token (114:26)
You may need an appropriate loader to handle this file type.
| 
|     // let data = { locale: _locale }
|     let data = { locale: {...default_locale, ...this.localeData}}
| 
|     data.monthDate = new Date(this.startDate)
 @ ./node_modules/vue2-daterange-picker/src/components/DateRangePicker.vue?vue&type=script&lang=js& 1:0-120 1:141-258
 @ ./node_modules/vue2-daterange-picker/src/components/DateRangePicker.vue

Can you fix it,

Thank you, best regards...

**Comment by erhansaydam** [comment]
Ok it's solved. When writing import line like this, no problem occurs:

`import DateRangePicker from 'vue2-daterange-picker'`

_In the usage part there says : 
import DateRangePicker from 'vue2-daterange-picker/src/components/DateRangePicker'_

**Comment by nkostadinov** [comment]
I will update the docs. That was the first version before I updated the package json file for easier import - 10x
