### ISSUE TITLE
In singleDataPicker change-month trigger changeLeftMonth ever

### ISSUE THREAD

**Issue by Luigidefra** [Innologica/vue2-daterange-picker#110]
In the case of singleDataPicker change-month have to trigger changeLeftMonth or changeRightMonth

<calendar :monthDate="monthDate"
                                      :locale-data="locale"
                                      :start="start" :end="end"
                                      :minDate="min" :maxDate="max"
                                      :show-dropdowns="showDropdowns"

                                      @change-month="changeLeftMonth"
                                      :date-format="dateFormatFn"

                                      @dateClick="dateClick" @hoverDate="hoverDate"
                                      :showWeekNumbers="showWeekNumbers"
                            ></calendar>

**Comment by nkostadinov** [comment]
I don't quite understand what you are asking exactly. But in case of single date picker only the "left" calendar is used.
