### ISSUE TITLE
Tab skips over date-range-picker and when open, not tab navigable.

### ISSUE THREAD

**Issue by potatowave** [Innologica/vue2-daterange-picker#113]
Assessing this for accessibility, currently the date-range-picker is out of the tab flow.

Additionally, when open, the calendar is not tab navigable.

What needs to be done to make this component accessible?

**Comment by nkostadinov** [comment]
I admit I didn't check fo accessibility when designing the package. I guess the dom needs to be updated. 
If you know what needs to be done you can make a PR, otherwise I will see if I can do it. Right now I'm going over the issues and preparing a new version.
