### ISSUE TITLE
Second calendar showing date, if more than 2 months difference is there in ranges.

### ISSUE THREAD

**Issue by divya-lb** [Innologica/vue2-daterange-picker#114]
I selected 'this year' in ranges, first calendar showing 1st Jan but second calendar showing some random month each time. How can i configure to show 31st Dec on second calendar.
![dateRangePiker](https://user-images.githubusercontent.com/40661980/71576041-3c0cc980-2b15-11ea-9336-898c22e2e38e.png)

**Comment by nkostadinov** [comment]
do you have any min/max values set ?

**Comment by divya-lb** [comment]
Yes i have, min_date: "2016-09-02", max_date: "2021-10-02"

**Comment by nkostadinov** [comment]
yes, that's not expected behavior. I will fix it

**Comment by divya-lb** [comment]
Thank you...

**Comment by nkostadinov** [comment]
I just released a new version today but could not reproduce your issue. I need more detailed steps to make this happen. Do you have linkedCalendars option unchecked. If you can write me the exact steps and values to reach to this state I will fix it :) . Also please check if the issue persists with the latest version. Thank you.
