### ISSUE TITLE
Next month not working

### ISSUE THREAD

**Issue by sourcenux** [Innologica/vue2-daterange-picker#115]
Hi,

the button used to change to the next month does not work when using your Example / Playground picker (https://innologica.github.io/vue2-daterange-picker/#usage). It does not work locally as well.  Configuration as shown in the screenshot below.  If you use the button nothing happens (also no error message). Tested with Firefox and Vivaldi. 

![grafik](https://user-images.githubusercontent.com/29550035/71587678-f48b3b00-2b1e-11ea-9de5-47589d51bce1.png)

**Comment by VKolegov** [comment]
Can confirm this issue

Tested with chrome, firefox and safari 
(macOS Mojave)

**Comment by DavudSafarli** [comment]
any solution?

**Comment by berkaygure** [comment]
I sent PR but not accept yet.

**Comment by mthottem** [comment]
Hi. Does this fix only work for single date range picker? I tried it for date range picker and it wasn't working.

**Comment by berkaygure** [comment]
@mthottem 
 It should work. You maybe forgot set to minimum and maximum date.

![video](https://user-images.githubusercontent.com/5683957/72416723-618e0a00-3788-11ea-8b95-18f6bd10bfa3.gif)
