### ISSUE TITLE
Calendar view broken with 'showWeekNumbers=false' and 'singleDatePicker=false'

### ISSUE THREAD

**Issue by karakum** [Innologica/vue2-daterange-picker#118]
Calendar panels rendered verticaly, there is no width for both horizontal(window width enough)

![изображение](https://user-images.githubusercontent.com/12033941/72068588-025b7000-3318-11ea-8610-c41b418d2b84.png)

![изображение](https://user-images.githubusercontent.com/12033941/72068727-523a3700-3318-11ea-807b-ed4981726ec6.png)

**Comment by nkostadinov** [comment]
Seems like a css bug. I will check it out

**Comment by adelinferaru** [comment]
```
                .calendars-container {
                    display: flex!important;
                    flex-direction: column;
                }

                @media only screen and (min-width: 720px) {
                    .calendars-container {
                        flex-direction: row;
                    }
                }
```

**Comment by nkostadinov** [comment]
I've uploaded update demo with the css problem fixed. Can you confirm if it is OK, so I can release a new version and close the issue.

**Comment by karakum** [comment]
Thanks, now looks better.
But some things is present:
![изображение](https://user-images.githubusercontent.com/12033941/72740901-30bf3200-3bd9-11ea-9376-46171c4d8445.png)

And there is space on right side when weeks not showed:
![изображение](https://user-images.githubusercontent.com/12033941/72741013-606e3a00-3bd9-11ea-9724-57cc1627dd22.png)
