### ISSUE TITLE
Calendar view broken when 'singleDatePicker=true'

### ISSUE THREAD

**Issue by ahirota** [Innologica/vue2-daterange-picker#121]
The latest version (v0.4.1) released fixed a previous CSS issue with  
```
.daterangepicker .calendars-container {
    min-width: 540px;
}
```
However, this breaks the CSS when using 'singleDatePicker=true' as seen below in the Example Playground.

![css-issue](https://user-images.githubusercontent.com/12651319/73039104-31d1b700-3e98-11ea-8a15-4ef6ff72c62c.png)

Since this was working in the previous version (v0.4.0), I'm not quite sure how to resolve both the previous CSS issue #118 and this one simultaneously.

**Comment by nkostadinov** [comment]
I'll fix it :) I missed that case obviously

**Comment by nkostadinov** [comment]
should be fixed now

**Comment by ahirota** [comment]
@nkostadinov thank you good sir!
