### ISSUE TITLE
Incorrectly changes to next month

### ISSUE THREAD

**Issue by waynetheonly** [Innologica/vue2-daterange-picker#122]
When the `singleDatePicker` has a truthy value and the `maxDate` is set to `2020-12-31` navigation through arrows doesn't work quite as expected. It should load December as a last available month, but instead it doesn't go past November.

![image](https://user-images.githubusercontent.com/15893174/73136565-af8ff100-4057-11ea-982f-9a335d9016d7.png)

Same issue can be reproduced in sandbox version of date range picker. Check the `singleDatePicker` checkbox, set `minDate` to `2020-01-01` and `maxDate` to `2020-12-31`. Watch it not go past November: https://innologica.github.io/vue2-daterange-picker/#usage

**Comment by nkostadinov** [comment]
fixed in release 0.4.3
