### ISSUE TITLE
On manual input, if numbers are added, the component goes NaN

### ISSUE THREAD

**Issue by Zurj** [Innologica/vue2-daterange-picker#127]
When the years are filled manually, the component behaves strangely.
It allows big numbers, as here:

![image](https://user-images.githubusercontent.com/13176864/73655448-c3120c00-4696-11ea-8b62-fbc17dccf2dd.png)

Then, when the numbers become really big, the component becomes non-responsive and fills the whole screen with NaNs.
![image](https://user-images.githubusercontent.com/13176864/73655383-9827b800-4696-11ea-8a5b-b1278474ac39.png)

**Comment by nkostadinov** [comment]
could you be more specific, where do you put this big numbers and what number makes the component filled with NaN

**Comment by Zurj** [comment]
Of course, look at the screenshots above. Click at the year picker/input element (with class="yearselect".  It has 2019 in the screenshot above) and manually input several times 1. You'll see the whole element go NaN.
