### ISSUE TITLE
ranges active is only applied to first match

### ISSUE THREAD

**Issue by gregg-cbs** [Innologica/vue2-daterange-picker#128]
Version: 0.4.2

### issue
If two ranges have the same dates, only the first matched range gets active.
This is different behaviour to previous versions.
In previous versions, all ranges with the same dates would get active class.

### example
In and amongst my ranges I have:
`'QTR TO DATE'` and `'YEAR TO DATE'`

At this time of the year both will yield the same date range: `01/01/2020 to 03/02/2020`.
In this case I would expect both ranges to be marked as active.

Because when i select `'YEAR TO DATE'` the picker is matching `'QTR TO DATE'` and not adding active to `YEAR TO DATE` .

### Possible change which affected this
https://github.com/Innologica/vue2-daterange-picker/commit/32d13a0ddf4af34d4c6c961c479925c2489fea1a#diff-c4d060d4de24f8467e690342f0804aa0

**Comment by nkostadinov** [comment]
Well I did not expect to put the same range twice :) I will see if I can "fix" this easily

**Comment by gregg-cbs** [comment]
I know, it's a weird use case. Thanks for looking at this, the team and I appreciate it.
