### ISSUE TITLE
Placeholder text when no date is selected

### ISSUE THREAD

**Issue by bajracharya-kshitij** [Innologica/vue2-daterange-picker#129]
Hello,
Thank you for this awesome component. Is there an option to show a placeholder text like "Select date range" at the beginning when no date has been selected? At the moment, I'm using it by setting startDate and endDate to blank strings, but that seems to be less informative.

**Comment by nkostadinov** [comment]
yes, you could override the input slot and display whatever you want :
```
        <date-range-picker ....>
          <div slot="input" slot-scope="picker" style="min-width: 350px;">
            {{ picker.startDate | date }} - {{ picker.endDate | date }}
          </div>
        </date-range-picker>
```
see https://innologica.github.io/vue2-daterange-picker/#slots

**Comment by bajracharya-kshitij** [comment]
@nkostadinov works perfectly. Thank you!
