### ISSUE TITLE
Clear selected dates

### ISSUE THREAD

**Issue by bajracharya-kshitij** [Innologica/vue2-daterange-picker#130]
Is there a way to clear the dates once they have been selected? I'm using auto-apply set to true.

**Comment by nkostadinov** [comment]
Yes, you just have to set the start and end dates to null.

**Comment by bajracharya-kshitij** [comment]
I meant is there a clear button like the apply button and the cancel button? Or a way to add our custom button in the component itself?

**Comment by nkostadinov** [comment]
In the latest version v0.4.6 there are two new slots header/footer. You can use them to add whatever buttons you want :)
