### ISSUE TITLE
DateRange Picker Broken 

### ISSUE THREAD

**Issue by mthottem** [Innologica/vue2-daterange-picker#132]
The date range picker seems broken after 0.4.4 release. The preselected ranges aren't working like "Today", "This Month", etc.

**Comment by nkostadinov** [comment]
they seem fine to me, may be there are min/max dates which interfere ? can you give an example

**Comment by mthottem** [comment]
<img width="695" alt="Screen Shot 2020-02-08 at 4 22 28 AM" src="https://user-images.githubusercontent.com/24368952/74085127-b2f98400-4a2a-11ea-96e2-76518f84dc5f.png">
That's what I see when I click one of the ranges.

My picker is set up as follows:
`<date-range-picker
    v-model="rangeData"
    :locale-data="{  direction: 'ltr', format: 'mm/dd/yyyy' }"
    :show-dropdowns="true"
    :linked-calendars="false"
    :ranges="ranges"
    :minDate="minDate"
    :maxDate="maxDate">
    <template v-slot:input="picker">
      <font-awesome-icon :icon="['fal', 'calendar']" class="fa-icon" />
      {{ getDisplayStartDate(picker.startDate) }} -
      {{ getDisplayEndDate(picker.endDate) }}
    </template>
  </date-range-picker>`

My ranges are:
`Today: [moment(), moment()],
        'Last week': [moment().subtract(1, 'week').startOf('week'), moment().subtract(1, 'week').endOf('week')],
        'Last month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')],
        'This month': [moment().startOf('month'), moment().endOf('month')],
        'This year': [moment().startOf('year'), moment().endOf('year')],
        All: [moment('1900-01-01'), moment('9999-01-01')],`
