### ISSUE TITLE
Year label is incorrect

### ISSUE THREAD

**Issue by pichicacax** [Innologica/vue2-daterange-picker#133]
The year displayed on the left calendar is incorrect when crossing years (e.g. from Feb 2020 to Dec 2019).  Seems like the data 'year_text' in component 'Calendar' is not updating properly.

![Screen Shot 2020-02-12 at 11 16 22 PM](https://user-images.githubusercontent.com/8698840/74349410-303c4480-4def-11ea-8945-b80c4bafebdb.jpg)

**Comment by sourcenux** [comment]
can confirm.
