### ISSUE TITLE
Date Range Picker: Allow selecting single day range with one click

### ISSUE THREAD

**Issue by gabriel-felipe** [Innologica/vue2-daterange-picker#134]
Currently, if you have:
```
:autoApply = false 
:singleDatePicker="false"
```
To select a range that starts and ends on the same day you need to click twice in the same that, if you click only once the apply button is disabled. I guess this isn't a bug, but I had some clients confused by this behavior.

It would be a nice UI addition if we could click on apply after having only the `start_date` selected and then the `end_date` would be assumed to be the same day.

Or maybe just improve the UI making it clearer that one other click over the same day is necessary.

![Screenshot from 2020-02-14 09-55-57](https://user-images.githubusercontent.com/4062651/74533397-3f66e380-4f10-11ea-9f71-fece34bed53a.png)

**Comment by nkostadinov** [comment]
thats what the "singleDatePicker" prop is for, if you set it to true you will have what you want.

**Comment by gabriel-felipe** [comment]
@nkostadinov Thanks for your answer. 

I know about the `singleDatePicker` option, but what I really wanted was to suggest an improvement to the user interface when that option is false. As I said at the main issue, I don't think that the current behavior is buggy, just that it could be clearer to non-tech people.

Closing this one since I don't know exactly how that could be fixed and you are right that having 2 fields would make it extra clear.

Thanks again for all your work on this project :)

**Comment by nkostadinov** [comment]
I see what you mean, and I will think of something to improve the UX. That needs to be some UI hint that the selection is started and a second input is needed. I just dont know how to do it yet - I have 2 options in my head. Either i should change the footer text indicating a second date is needed or change the selected css of the first date to something which clearly indicates that this is the first date only - may be background color to only half of the "square" or something ...

**Comment by gabriel-felipe** [comment]
Yes, that's exactly what I thought. If you agree that this would be an actual improvement let me know and I can try some patches from here for a PR.

A tooltip/title at the disabled apply button could also be a clean option, would be hidden until the user tries to apply.
