### ISSUE TITLE
Click on ranges option not working

### ISSUE THREAD

**Issue by wakamin** [Innologica/vue2-daterange-picker#138]
This issue happened on version 0.4.3 and 0.4.4.

Clicking on ranges option is not working, it empty the v-model, not select the expected daterange.

this is my ranges object, it works on version 0.4.2 and prior version.

```
ranges: {
    Today: [moment(), moment()],
    Yesterday: [
        moment().subtract(1, "days"),
        moment().subtract(1, "days")
    ],
    "Last week": [
        moment()
            .subtract(1, "week")
            .startOf("week"),
        moment()
            .subtract(1, "week")
            .endOf("week")
    ],
    "This month": [
        moment().startOf("month"),
        moment().endOf("month")
    ],
    "Last month": [
        moment()
            .subtract(1, "month")
            .startOf("month"),
        moment()
            .subtract(1, "month")
            .endOf("month")
    ],
    "This year": [
        moment().startOf("year"),
        moment().endOf("year")
    ]
}
```

**Comment by Ri96** [comment]
Same Issue, I'm facing. please provide a solution.

**Comment by nkostadinov** [comment]
did you try passing :date-util='moment' in the props. If not I still need to look at it though.

**Comment by wakamin** [comment]
Adding :date-util='moment' props into date-range-picker got this error
`Property or method "moment" is not defined on the instance but referenced during render`

**Comment by nkostadinov** [comment]
Sorry it is a string so it should be date-util="moment" or :date-util='"moment"'

**Comment by Allyans3** [comment]
The same problem on 0.4.3 - 0.4.4. Please fix it. **date-util="moment" or :date-util='"moment"'** didn't help/

**Comment by nkostadinov** [comment]
fixed in 0.4.5. If you want to use moment you MUST specify date-util="moment".

**Comment by ipa1981** [comment]
@nkostadinov What if I face the same issue without using moment with custom range.: I use dayjs though:

```
datePickerRanges = {
	'Today': [dayjs(), dayjs()],
	'Yesterday': [dayjs().subtract(1, 'days'), dayjs().subtract(1, 'days')],
	'This month': [dayjs().startOf('month'), dayjs().endOf('month')],
	'Last month': [dayjs().subtract(1, 'month').startOf('month'), dayjs().subtract(1, 'month').endOf('month')],
	'This week': [dayjs().startOf('week'), dayjs()],
	'Last week': [dayjs().subtract(1, 'week').startOf('week'), dayjs().subtract(1, 'week').endOf('week')],
	'This year': [dayjs().startOf('year'), dayjs().endOf('year')],
	'All time': [dayjs().set('year', 2017).startOf('year'), dayjs()],
}
...
<date-range-picker v-model="dateRange" opens="left" :ranges="datePickerRanges" @update="changeDate" />
```

Any ideas?

**Comment by nkostadinov** [comment]
you can always cast them to date or timestamp so that the component handles them correctly. In your case you can add .toDate() to all of the dayjs calls e.g :
`dayjs().subtract(1, 'days').toDate()`

**Comment by ipa1981** [comment]
@nkostadinov Thanks for the explanation. It works now.

**Comment by svkmedia** [comment]
Thank you. Please add it to docs because I was stuck on this for 2 hours :)
