### ISSUE TITLE
Issue with setting default StartDate endDate

### ISSUE THREAD

**Issue by vik0803** [Innologica/vue2-daterange-picker#14]
Hi,

First of all thanks for sharing this date range picker. 

I have an issue with setting the default value of StartDate and EndDate. 

in Data: 

`data() {
            return {
                startDate: '2017-09-05',
                endDate: '2017-09-15',
                locale: {
                    direction: 'ltr', //direction of text
                    format: 'MM-DD-YYYY', //fomart of the dates displayed
                    separator: '-', //separator between the two ranges
                    applyLabel: 'Apply',
                    cancelLabel: 'Cancel',
                    weekLabel: 'W',
                    customRangeLabel: 'Custom Range',
                    daysOfWeek: moment.weekdaysMin(), //array of days - see moment documenations for details
                    monthNames: moment.monthsShort(), //array of month names - see moment documenations for details
                    firstDay: 1 //ISO first day of week - see moment documenations for details
                }
            }
}`

whereas when I try the same value retrieving from database in same format via momentjs as below in the mounted stage of vue.

`moment(this.reportInfoData.vs_from).format('YYYY-MM-DD');`

it display calendar as NaN value across all the dates and month name. 

Any help on this is highly appreciated.

Thanks,
Vik

**Comment by nkostadinov** [comment]
This doesn't happen as I test it here. Could you provide more info and example of the problem (may be jsfiddle).  What is the data format coming from then database database ?

**Comment by nkostadinov** [comment]
Cannot reproduce
