### ISSUE TITLE
Need Date Filter

### ISSUE THREAD

**Issue by mghako** [Innologica/vue2-daterange-picker#140]
i'm having this console error . i need date filter and where can i get that.

[Vue warn]: Failed to resolve filter: date

**Comment by nkostadinov** [comment]
There is no date filter in the component, at least in the latest version. Which version are you using ?

**Comment by mghako** [comment]
![test](https://user-images.githubusercontent.com/51154150/75777420-587ee980-5d84-11ea-8fe8-9e0b3e360acc.PNG)

version that i`m using is "vue2-daterange-picker": "^0.4.4",

**Comment by nkostadinov** [comment]
That's just for the demo. There is local date filter which takes param a date object and formats it. It is not required to use the component. If you want you can create you own. The demo uses this filter: 
```
.....
    filters: {
      date (value) {
        if (!value)
          return ''

        let options = {year: 'numeric', month: 'long', day: 'numeric'};
        return Intl.DateTimeFormat('en-US', options).format(value)
      }
    },
.....
```

**Comment by mghako** [comment]
thank you.. :D
