### ISSUE TITLE
Clear selected dates on clicking Cancel

### ISSUE THREAD

**Issue by ntabakova** [Innologica/vue2-daterange-picker#142]
Hello!

Thank you for the nice range datepicker :)

A quick question - i want to be able to clear the updated dates on Cancel - cancel clears the selected dates, but if you've clicked Apply, cancel doesn't clear the dates. Any help would be appreciated! :)

**Comment by nkostadinov** [comment]
Clearing the date means just set startDate and endDate to null. You can put you cancel button via the slot(footer) and change it's behavior. 
Cancel doesnt clear them if you have already selected the dates because ... it is cancel, not clear :)
