### ISSUE TITLE
Show custom range label on list of ranges

### ISSUE THREAD

**Issue by ntabakova** [Innologica/vue2-daterange-picker#143]
When calendars are always shown, is it possible to have the custom range label as part of the menu of preset ranges?

**Comment by nkostadinov** [comment]
well, it doesnt make any sense since the custom range just shows the calendars so you can select whatever you want. But I you have already show the calendars it wont do nothing more

**Comment by ntabakova** [comment]
I agree, but i'm following a design :)

**Comment by nkostadinov** [comment]
I guess you can override the slot "ranges" then and do whatever you want :)
