### ISSUE TITLE
Can't hide the first calendar

### ISSUE THREAD

**Issue by sasbass** [Innologica/vue2-daterange-picker#145]
When I have two fields the first calendar can't be hide when I try to open the second calendar.

**Comment by DezrtRose** [comment]
I am facing this same issue in one of my projects. Did you find any workarounds for this?

**Comment by nkostadinov** [comment]
Can you elaborate here, I dont think I understand the problem corretly ?

**Comment by alexanderArsenault** [comment]
when you have multiple calendar components on the same page, you can not close any/all other open calendars when opening a new one

**Comment by DezrtRose** [comment]
> Can you elaborate here, I dont think I understand the problem corretly ?

The issue is that when we have two or more pickers in same page and when we try to open one picker after another, the first one does not close. Is there any way to work around this or I am missing something here?

**Comment by nkostadinov** [comment]
I see the problem. I'm on it :)
