### ISSUE TITLE
Add Recent Days feature

### ISSUE THREAD

**Issue by vbenavente** [Innologica/vue2-daterange-picker#147]
Allow ability of recent days feature. Custom range could have the option to enter a number of days to go back instead of being required to to select a date. 
That way if you want to look at something 56 days back, you don't have to figure out what that date is you can just type in 56.

**Comment by nkostadinov** [comment]
I guess you can override the ranges slot and add a custom range picker where you can do this. Please take a look here https://innologica.github.io/vue2-daterange-picker/#slots
