### ISSUE TITLE
Closing calendar on "blur" event

### ISSUE THREAD

**Issue by Lamberthassel** [Innologica/vue2-daterange-picker#149]
I want to add some accessibility to this component by wrapping it with an HTML element that has `tabindex` attribute and that makes calendar open/close on `focus`/`blur` events. It looks like: 
```
<div tabindex="0" @focus="openPicker" @blur="closePicker>
    <DateRangePicker ... />
</div>
```

The problem is since month and range selecting buttons have `tabindex` attributes clicking them fires the root component blur event, which makes the date picker close.

Is it possible to make these `tabindex` attributes optional (e.g. via props)?
I could make a PR if you wish.

I think this issue is related to this commit: https://github.com/Innologica/vue2-daterange-picker/commit/49161ab51dca15f0ffaedc068b1c9422e47076da

**Comment by nkostadinov** [comment]
I've deployed a new version (0.5.1) which has appednToBody prop. I think if you set it to true it will fix your problem. Haven't tested it though.
