### ISSUE TITLE
Documentation around custom ranges

### ISSUE THREAD

**Issue by dwatts3624** [Innologica/vue2-daterange-picker#150]
First, I love this component!  Nice work! 

I found this by looking at the code and searching issues but thought it might be helpful to update the documentation around custom ranges to show that it takes an array for each key.

I think just showing this would be enough to get the point across:

```js
{
  'Today': [new Date(), new Date()]
}
```

Currently it just shows this which I don't think is valid JS:

```js
{
    'Today',
    'Yesterday',
    'This month',
    'This year',
    'Last week',
    'Last month',
}
```

**Comment by nkostadinov** [comment]
I've updated the documentation. These are the keys - the values is an array with 2 date objects or timestamps.
