### ISSUE TITLE
Choosing a range does not show correct end month

### ISSUE THREAD

**Issue by gregg-cbs** [Innologica/vue2-daterange-picker#151]
Hi,

I have noticed a minor bug when choosing a range that is the beginning of one month and end of another.

Version: 0.4.6

Screenshot:
<img width="701" alt="Screenshot 2020-03-31 at 08 34 42" src="https://user-images.githubusercontent.com/57114335/77999509-ad356600-732a-11ea-8fe9-096d79faf312.png">

Screen recording:
[Screen Recording 2020-03-31 at 08.30.14.mov.zip](https://github.com/Innologica/vue2-daterange-picker/files/4407409/Screen.Recording.2020-03-31.at.08.30.14.mov.zip)

Looks similar to this issue:
https://github.com/Innologica/vue2-daterange-picker/issues/74

Thanks!

**Comment by nkostadinov** [comment]
That's how the component works. The calendar are linked and the right one always shows "next" month unless linkCalendars prop is set to false and you manually move the right month.

**Comment by nkostadinov** [comment]
I might make the right calendar select the end of range when linkedCalendars is false.
