### ISSUE TITLE
Label slot for the Daterange-picker

### ISSUE THREAD

**Issue by RayVector** [Innologica/vue2-daterange-picker#152]
### I think this module needs a "label" template-slot for opening modal window with calendar.

**Comment by nkostadinov** [comment]
I dont understand , what do you mean by label slot ?

**Comment by RayVector** [comment]
`
<span class="calendar-label" @click=openCalendar>{{label}}</span>
<date-range-picker...>
`

I want the calendar to open by clicking on this "label", can you add <slot name="label"> ?

**Comment by RayVector** [comment]
![label](https://user-images.githubusercontent.com/43655985/82997723-6c4a8c80-a00f-11ea-8de8-02ced3e840f4.png)

Simply put, clicking on this button should open the calendar. I didn't find this methods/solves in your documentation.

**Comment by RayVector** [comment]
Need more info? Or you forgot abo my feature?)))

**Comment by nkostadinov** [comment]
you dont need a slot for that. You can open the picker if you put a ref on it. And then you can use anywhere this snippet(if your ref is "picker")

`this.$refs.picker.togglePicker(true/false)`
