### ISSUE TITLE
Displayed time in picker doesn`t match v-model

### ISSUE THREAD

**Issue by bsc-lgott** [Innologica/vue2-daterange-picker#153]
I think i found a little bug.
When opening the blank picker, time-values in the selects are set to the current user-time.
In v-model the time stays at 12am when you apply the date selection. 
To get the correct time value reflected in v-model you need to change the from and to time at least once.

**Comment by nkostadinov** [comment]
Yes, you are right. The time should be displayed when there is no date selected. I will fix it.
