### ISSUE TITLE
How to add custom ranges?

### ISSUE THREAD

**Issue by arnab-bhattacharjee-codeclouds** [Innologica/vue2-daterange-picker#159]
Hello,
I installed vue2-daterange-picker. But now I wanted to add custom ranges like

![image](https://user-images.githubusercontent.com/59700656/80371917-4c109c00-88b0-11ea-9020-bf45756ad33f.png)

I added the ranges but couldn't find any documentation for how to make them work. After that, I found this link https://codespots.com/library/item/1127. But the model is given null values on startDate and endDate.

**Comment by kardagan** [comment]
look at : https://github.com/Innologica/vue2-daterange-picker/issues/24

**Comment by nkostadinov** [comment]
I will make documentation more clear regarding ranges.
