### ISSUE TITLE
Default hour is 12:00PM

### ISSUE THREAD

**Issue by dudif91** [Innologica/vue2-daterange-picker#162]
when i choose range from the calendar the hour is set to 12:00.
working with time picker = false.

something like this: 
Thu Apr 09 2020 12:00:00 GMT+0300 - Thu Apr 11 2020 12:00:00 GMT+0300

but i think it should be:
Thu Apr 09 2020 00:00:00 GMT+0300 - Thu Apr 11 2020 23:59:00 GMT+0300

**Comment by nkostadinov** [comment]
the ranges are predefined that way. You can override them however you like. see the ranges prop in the docs

**Comment by Xsmael** [comment]
what if you dont uses predifined ranges like these: 

`{
    'Today': [today, today],
    'Yesterday': [yesterday, yesterday],
    'This month': [thisMonthStart, thisMonthEnd],
    'This year': [new Date(today.getFullYear(), 0, 1), new Date(today.getFullYear(), 11, 31)],
    'Last month': [new Date(today.getFullYear(), today.getMonth() - 1, 1), new Date(today.getFullYear(), today.getMonth(), 0)],
}`

but just by selecting a custom range from the date picker, how to set default start time and end time ?, i want for example start time: 00:00:00 and end time 23:59:59

**Comment by nkostadinov** [comment]
I'm using it with these time myself. I apply the times after selection, the user only select the dates.
