### ISSUE TITLE
Footer & Header slots are not working

### ISSUE THREAD

**Issue by manisha-500** [Innologica/vue2-daterange-picker#165]
I'm facing issue with header and footer slot even the basic text is not reflecting but input and ranges slots are working fine absolutely .I'm using slot like this provided the code below
```
<template #input>input slot</template> <template #ranges>ranges slot</template>
<template #header>header slot</template> <template #footer>footer slot</template>

```
Can anyone help me with this.

**Comment by nkostadinov** [comment]
what version of Vue are you using. Can you try with the old slot syntax <template slot="header">...

**Comment by manisha-500** [comment]
Vue version is 2.6.8 and with the old syntax also I got the same problem header, footer slots are not working but input and ranges are working perfectly.
Can you provide sample which worked for you.

**Comment by nkostadinov** [comment]
I'm the author so I think I will create demo usage of the slots and upload it to the help page :)

**Comment by manisha-500** [comment]
Thank you
