### ISSUE TITLE
Showing the same month twice for this month

### ISSUE THREAD

**Issue by kavin404** [Innologica/vue2-daterange-picker#167]
![clandar issue](https://user-images.githubusercontent.com/26364290/81897168-baa16980-95d3-11ea-9962-87cb23de1525.PNG)
`
Does anyone know how to correct this?

**Comment by nkostadinov** [comment]
can you give the values you parss to the component in order to get this (start,end, min date, max date)

**Comment by nkostadinov** [comment]
cannot reproduce with the lates release
