### ISSUE TITLE
How to recognize if one of the shortcut ranges are being invoked?

### ISSUE THREAD

**Issue by PerpetualWar** [Innologica/vue2-daterange-picker#169]
My api needs when shortcut range is invoked for me to send them not range of dates, but certain strings.

How could I do that, it would be nice if I could get event sent when shortcuts are invoked, so I could do extra logic but I don't see it in docs?

Any other recommendations?

**Comment by PerpetualWar** [comment]
BTW, I tried hoverDate event but it does not work on shortcuts.

**Comment by nkostadinov** [comment]
you mean you want to know when someone clicks on a range instead of picking dates ?

**Comment by PerpetualWar** [comment]
yes, in order to prepare different payload instead of standard date range.

**Comment by nkostadinov** [comment]
One way is to use the ranges slot input and put something yours which you can handle like you want, or you could just wrap around the "CalendarRanges" component bundled with the extension. 

The other way is to just analyze the selected date to check if start and end dates match exactly as one of the ranges

**Comment by PerpetualWar** [comment]
I will definitely try your first recommendation, but second one won't work as I need range lastweek for example to return string lastweek, but if you manually select last week in picker, it should return proper start and end date range.

**Comment by PerpetualWar** [comment]
@nkostadinov I would appreciate if you can provide example of using ranges slot with custom values(strings) instead of dates.
