### ISSUE TITLE
Using `firstDay != 0` is modifying the locale parameter `daysOfWeek` 

### ISSUE THREAD

**Issue by alexanderschulze** [Innologica/vue2-daterange-picker#176]
I am using a global locale object for all instances of the daterange picker with the `firstDay = 1` option to display Monday to be the first day of week.

In [[1]](https://github.com/Innologica/vue2-daterange-picker/blob/6a80f28eb5db024ba635ec9d0e8ab4aafb726abb/src/components/DateRangePicker.vue#L454) the source `daysOfWeek` array is shifted by the provided value in `firstDay`.

As a result, a second instance of the daterange picker is not using [S,M,T,W,T,F,S] anymore, but the shifted array [M,T,W,T,F,S,S], and a third instance [T,W,T,F,S,S,M], and so on.

Therefore, the weekdays in the header do not match with the days anymore.

**Comment by Lootjs** [comment]
any ideas?

**Comment by nkostadinov** [comment]
this should be fixed now. Can you confirm ?
