### ISSUE TITLE
AutoApply seems to be not working with the timepicker

### ISSUE THREAD

**Issue by oprokidnev-apica** [Innologica/vue2-daterange-picker#178]
When I'm using the datepicker with timepicker enabled and autoApply I assume to update the time just after timepicker selector was changed.

Ways to reproduce:
1.Enable auto apply and timepicker in the playground https://innologica.github.io/vue2-daterange-picker/#example-playground
2. Try to pick time (if there is no button to apply time selected is reverted if I try to unfocus the datepicker component)

**Comment by oprokidnev-apica** [comment]
Would you mind me to bump this question up a bit?
I made a PR that solves this issue: https://github.com/Innologica/vue2-daterange-picker/pull/179

**Comment by bryanmendoza** [comment]
yeah im still having this problem..
autoUpdate doesnt trigger when you change time
