### ISSUE TITLE
Calendar not updating on programatic date change

### ISSUE THREAD

**Issue by mthottem** [Innologica/vue2-daterange-picker#180]
The date picker doesn't seem to update with the correct month, date, year if you programmatically or manually change the date that is displayed on the picker.

**Comment by nkostadinov** [comment]
can you give an example

**Comment by mthottem** [comment]
<img width="808" alt="Screen Shot 2020-06-18 at 8 18 40 PM" src="https://user-images.githubusercontent.com/24368952/85093400-09c55600-b1a1-11ea-93f6-c528facb81e8.png">
<img width="876" alt="Screen Shot 2020-06-18 at 8 18 47 PM" src="https://user-images.githubusercontent.com/24368952/85093409-0c27b000-b1a1-11ea-888c-d164413d72cd.png">
<img width="892" alt="Screen Shot 2020-06-18 at 8 22 20 PM" src="https://user-images.githubusercontent.com/24368952/85093535-6e80b080-b1a1-11ea-903d-2257631988ca.png">

The dates are changing in the backend but it doesn't reflect in the UI. So we can't see the new dates unless we manually scroll there ourselves.

**Comment by brianjac2325** [comment]
I am having the same issue.  Has this been fixed or is there a work around?

**Comment by TheHussein** [comment]
Any update on this from maintainers?

**Comment by nkostadinov** [comment]
@TheHussein maintaner here :) I've been really busy lately so havent done anything on the issue, but I promise to check this today as it seems like a bug

**Comment by nkostadinov** [comment]
I think its ok now

**Comment by vitalii-bilyi-zp** [comment]
doesn't work when changing date programmatically

**Comment by Rizayev** [comment]
```
 <date-range-picker
          ref="rangePicker"
      </date-range-picker>
```
1. add ref
2. Import momentjs
3. 
```
this.$refs.rangePicker.monthDate =moment(START_DATE).toDate()
this.$refs.rangePicker.nextMonthDate = moment(END_DATE).toDate()
```

**Comment by nkostadinov** [comment]
@Rizayev this will work but is not recommended way to change the displayed month. In current release the picker should select the correct month.
