### ISSUE TITLE
Calendar position is off

### ISSUE THREAD

**Issue by mthottem** [Innologica/vue2-daterange-picker#181]
The calendar isn't opening near the input. There's a top:100px in the .daterangepicker CSS that seems to be causing the issue.
<img width="876" alt="Screen Shot 2020-06-18 at 8 18 47 PM" src="https://user-images.githubusercontent.com/24368952/85094414-9a049a80-b1a3-11ea-8612-e047572cc934.png">

**Comment by quanghm27** [comment]
@mthottem: I faced this issue too when use prop :append-to-body="false"

**Comment by quanghm27** [comment]
@mthottem: now, I use deep selector for change style:
```
  .vue-daterange-picker ::v-deep .daterangepicker {
    top: 36px;
  }
```
Looking forward for better solution

**Comment by nkostadinov** [comment]
I set `top:auto` and now it seems fine.
