### ISSUE TITLE
On autoApply, calender is closing before we select time when timePicker is true

### ISSUE THREAD

**Issue by tito300** [Innologica/vue2-daterange-picker#184]
When timePicker is set to true while autoApply is true, it doesn't allow to select time before closing. It will close and then the user has to reopen it to change time. 

maybe time needs to be zeroed out by default and once its set then the calender is closed automatically

**Comment by nkostadinov** [comment]
i think its not a good idea to close the picker only after time is updated. it will be bad UX. He can change minute/hour/date in any order - when to close it ?
