### ISSUE TITLE
The date range picker doesn't support reverse selection

### ISSUE THREAD

**Issue by vineetgupta1991** [Innologica/vue2-daterange-picker#185]
The date range picker doesn't support reverse selection like selecting endDate first before startDate. Good to have one such property something like "allowReverseSelection. 
Currently, it supports only forward selection. 
Would be good if we inherit their feature below :
https://www.telerik.com/kendo-react-ui/components/dateinputs/daterangepicker/reverse/

**Comment by nkostadinov** [comment]
yeah, may be I will implement something like that.

**Comment by faisalindrianto** [comment]
does anyone have workaround on this? need this feature too

**Comment by nkostadinov** [comment]
I did the inverse selection in my working branch. I will release it soon.
