### ISSUE TITLE
Conflict with Bootstrap Vue menu - will not present

### ISSUE THREAD

**Issue by robertdeboer** [Innologica/vue2-daterange-picker#187]
When using this component along side Bootstrap Vue it appears there is a collision between css styling of the separate elements that cause the date range picker to now show.

How to reproduce:
1. Create a vue project with Bootstrap Vue and this component
2. Use the Boostrap vue navbar component on the same page you are using the datepicker. Using the examples as a setup point for the date picker
3. Attempting to select the input containing the dates does not bring up the date picker.

When looking at the page elements, it appears both the Bootstrap Vue navbar and date picker are uisng the same CSS classes and the collision is causing non-standard formatting of the date picker - keeping the display to none, position to abolusion, etc

![image](https://user-images.githubusercontent.com/446001/87842642-d0edcf00-c87b-11ea-8012-c2d9bfa06822.png)

**Comment by rodsouto** [comment]
`.dropdown-menu` only adds `padding: 0;`, would it be fine to remove this class to avoid the conflict with bootstrap?

**Comment by robertdeboer** [comment]
You can try. I'm not 100% sure

**Comment by pkerspe** [comment]
same issue here. Removing the class "dropdown-menu" results in the calendar showing up, yet not being absolutely positioned, messing up the layout of the page

**Comment by pkerspe** [comment]
I had to add this css definition to my components style to display the calendar correctly in the above mentioned constelation:
```
    .daterangepicker .calendar-table td, .daterangepicker .calendar-table th {
        padding:0;
    }
```

**Comment by nkostadinov** [comment]
@pkerspe haha I mean that the CSS must be imported manually so that if you want to override it you dont have to include it :) May be its not clear. 

Anyway I will test and add your fix to the component css.

**Comment by nkostadinov** [comment]
I removed the bootstrap "dropdown-menu" class
