### ISSUE TITLE
thank u for this wonderful component, does it support other languages because i want to change the ranges text to french ? 

### ISSUE THREAD

**Issue by AmineAlyate** [Innologica/vue2-daterange-picker#188]
i want to change the ranges text to french and I could't can any one help me please ?
'Today' to 'aujourd hui'
Yesterday' to 'hier'
...

**Comment by nkostadinov** [comment]
Yes the ranges with the english titles are just default value to the ranges array prop. Look for "ranges" in the documentation. It is well described: https://innologica.github.io/vue2-daterange-picker/#props
