### ISSUE TITLE
left calendar is not based on startDate when Calendar is opened 

### ISSUE THREAD

**Issue by heykkyu** [Innologica/vue2-daterange-picker#193]
![image](https://user-images.githubusercontent.com/46082226/88905642-7435df80-d291-11ea-9d74-f4a400ff2073.png)

I set the StartDate for 2019-12-10 and EndDate for 2019-12-20.
It means that left calendar should be shown December month when I clicked and opened the calendar popup. 
Even though vue2-daterange-picker isn't work correctly but Date Range Picker is works very well.

Would you like to give me the answer?

**Comment by zainkhalid93** [comment]
Looks like you have linked calendars, to fix it, set linkedCalendars to false when passing a prop.

**Comment by zhnoah** [comment]
I have the same problem, that “linkedCalendars: false” doesn't solve.

**Comment by ousmaneNdiaye** [comment]
Same problem for me :(

**Comment by zcattacz** [comment]
The behavior has more twists in my case: 

when the page is first loaded, if one programmatically set a date range in last year, the drop down calendar will not update, 

but if one selected a date range and clicked `apply`, after that, the drop-down  calendar will correctly reflect date-range set programmatically. this didn't work with auto-apply in my case.

in any case the date is set to activate  on calendar, its just that ppl have to click through to that month, to see that date activated.
thus testing with date from current month date will not reveal this problem.

**Comment by nkostadinov** [comment]
I believe the problem is related due to the fact that the dates are outside of the range of min and max date. When this is true the calendar show the nearest month inside the min/max range. I don't know ... may be its a bit confusing and I will allow navigation outside of min/max but not allow selection.
