### ISSUE TITLE
Only show one calendar.

### ISSUE THREAD

**Issue by TheFrankman** [Innologica/vue2-daterange-picker#194]
Am i missing something here, or is there no way to only have a single calendar ?

I still want to do a date range, but I only want to show a single calendar as it's a complete nightmare on mobile.

**Comment by iomariani** [comment]
There's a `single-date-picker` boolean prop you can use for that.

**Comment by iomariani** [comment]
Seems there's a PR #190 regarding this, haven't tried though.

**Comment by nkostadinov** [comment]
PR is merged and it is working in v 0.6
