### ISSUE TITLE
Date formats filter do not seem to work

### ISSUE THREAD

**Issue by MaksymShokin** [Innologica/vue2-daterange-picker#195]
<template #input="picker" style="min-width: 350px;">
     {{ picker.startDate | date }} - {{ picker.endDate | date }}
   </template>

    filters: {
      date(val) {
        return val ? val.toLocaleString() : ''
      }
    }

I tried to implement date formatting using filters like it was shown in the demo. But it has no effect, even filter method is not called. Could you check if there are any issues with it?

**Comment by nkostadinov** [comment]
I tried it and it is working . This seems ok, the problem is not from the component.
