### ISSUE TITLE
Component not responsive?

### ISSUE THREAD

**Issue by srdjan-medjo** [Innologica/vue2-daterange-picker#203]
So in mobile view components go out of bounds..... What's recommended way of dealing with this?

**Comment by nkostadinov** [comment]
At what resolution the component goes out of bounds ?

**Comment by srdjan-medjo** [comment]
Approximately, 650px width.... so at mobile width its cut in half (other month picker and shortcuts are completely cut). Ideally they would rearrange in vertical? Or if I could turn off one of the two month pickers and shortcuts that could help as well.

**Comment by nkostadinov** [comment]
there is a prop "singleDatePicker" which does that - turns off the second picker. But your scenario should be handled as you say - the pickers should align vertically - i will check it.

**Comment by hiren004** [comment]
Yes, I have the same issue while I checking it with the mobile view, it should be vertically. Right now, I'm getting it horizontal and that's why getting scrollbar. Happy if it's fixed very soon!

Thanks for this great component!
Cheers :)

**Comment by hiren004** [comment]
@nkostadinov @srdjan-medjo 
This CSS works for me fine now, try this one:

```
.daterangepicker .calendars-container {
  display: flex;
  flex-wrap: wrap;
}
.drp-calendar .col .left {
  flex: 0 0 auto;
}
```

**Comment by nkostadinov** [comment]
Looks fine. I think I will add it to the scss. 10x

**Comment by virajdaffodil** [comment]
changeing flex-basis to 1 in .col class fixed the issue

**Comment by junjizhi** [comment]
The time range picker also ran into responsiveness issues when screen size is less than 800px. The pre-defined ranges stacks on top of the pickers because of the `flex-wrap: wrap` CSS property (I attached my fix at the end):

![image](https://user-images.githubusercontent.com/2715151/118984068-1cb14f00-b94b-11eb-830a-33efcf37dd69.png)



The code looks like below:

```vue
      <date-range-picker
        ref="picker"
        v-model="dateRange"
        :opens="opens"
        :locale-data="{ firstDay: 1, format: 'yyyy-mm-dd HH:MM' }"
        :single-date-picker="true"
        :time-picker="true"
        :time-picker24hour="true"
        :show-week-numbers="false"
        :show-dropdowns="false"
        :auto-apply="false"
        :ranges="predefinedRanges"
        :linked-calendars="true"
        :always-show-calendars="true"
        :append-to-body="false"
        :close-on-esc="true"
        @select="updateDate"
      >
        <template
          v-slot:input="picker"
          style="min-width: 350px;"
        >
          <div v-if="ifPredefinedRange">
            {{ rangeLabel }}
          </div>
          <div v-if="ifCustomRange">
            {{ picker.startDate | date }} - {{ picker.endDate | date }}
          </div>
        </template>
        <template v-slot:ranges="ranges">
          <div class="ranges">
            <ul>
              <li
                v-for="(range, name) in ranges.ranges"
                :key="name"
                @click="ranges.clickRange(range), updateRangeLabel(name)"
              >
                {{ name }}
              </li>
            </ul>
          </div>
        </template>
      </date-range-picker>
```

The hack I did was:

```vue
<style>
.calendars {
  flex-wrap: nowrap !important;
}

@media only screen and (max-width: 800px) {
  .calendars > .ranges > ul > li {
  text-align: right;
  }
}
</style>
```
