### ISSUE TITLE
Component not opening inside Web Component

### ISSUE THREAD

**Issue by kenger** [Innologica/vue2-daterange-picker#207]
I'm trying to use this component inside a Web Component but when you click it immediatly close.

![bug-range-picker](https://user-images.githubusercontent.com/6430867/94168889-687c2900-fe8e-11ea-808e-9a6f9bf2c396.gif)

When the same component is used inside yarn serve it works.

REPRODUCTION
Component
```
<template>
    <span class="date-range-picker">
        <date-range-picker v-model="dates" opens="right" />
    </span>
</template>

<script>
import DateRangePicker from "vue2-daterange-picker";

export default {
    components: { DateRangePicker },
    data() {             
        return {
            dates: {
                startDate: new Date("2020-01-01T00:00:00+0000"),
                endDate: new Date(),
            },
        };  
    },

};
</script>

<style src="vue2-daterange-picker/dist/vue2-daterange-picker.css"></style>
```

Command
vue-cli-service build --target wc --inline-vue --name test-component "src/TestDateRangePicker.vue"

**Comment by kenger** [comment]
Looking at the code I think the problem is in [this line](https://github.com/Innologica/vue2-daterange-picker/blob/master/src/components/DateRangePicker.vue#L602). 

In the Web Component $event.target seems to always  be the WebComponent itself because of ShadowDOM so every click count as both a "onClickPicker" and a "clickAway".

**Comment by nkostadinov** [comment]
I tested it and you are right. But this is not the only problem with web components. I tried it but clicking anywhere would also close the component so it not an easy change. I dont have time to fix this. Just use it as a vue component.
