### ISSUE TITLE
Predefined ranges and update

### ISSUE THREAD

**Issue by epchristi** [Innologica/vue2-daterange-picker#209]
First, thank you for the work on this project. I am using and will be watching this project. 
In the base bootstrap daterangepicker, the update allows start, end and label to be returned. This is very useful if the "predefined" ranges are used.
It also seems that with this component, "moment" can't be used to set the predefined ranges. This is a pretty big hinderance, since "moment" has become a "defacto" standard for javascript date handling.

**Comment by epchristi** [comment]
I saw in another issue, from earlier, that "toDate" can be used on the moment object to get the desired result. (but supporting moment by default would be ideal.)

**Comment by nkostadinov** [comment]
Use toDate if you want to use moment.js. In the new versions I will remove moment from the dependencies because it's too big.
