### ISSUE TITLE
Change value format

### ISSUE THREAD

**Issue by jupa8712** [Innologica/vue2-daterange-picker#213]
Hi, How can I change this format in data ranges values "Mon Oct 12 2020 00:00:00 GMT-0500 (Colombia Standard Time)" to "2020-10-12"? Is it possible? Thanks

**Comment by nkostadinov** [comment]
the component returns date objects. You can use whatever date time library you are using to format it the way you want.

**Comment by Xsmael** [comment]
> the component returns date objects. You can use whatever date time library you are using to format it the way you want.

Can you please provide a source code example ? That would be usefull

thanks
