### ISSUE TITLE
Vue3 Support and is it possible to disallow daterange selection over specific dates?

### ISSUE THREAD

**Issue by Inasyah** [Innologica/vue2-daterange-picker#216]
Hi :), I have two questions:

Is there any plan to update this to Vue3 or will it work without any changes?

Is it possible to disallow a daterange selection over specific dates?
For example with a class 'range-stop' that stops the daterange selection over this date:
Date 12.12.2020 has the class 'range-stop' and if the user selects a date before as the start date, they can't select any date after as the end date. (For my use-case this has to be a new class and can't be the same as 'disabled')

PS: thank you for this great tool!

**Comment by nkostadinov** [comment]
Yes I have plans for vue 3 but cannot give ETA yet. 

There is example on the demo page which shows how you can disallow a daterange selection over specific dates.
