### ISSUE TITLE
single-date-picker="range" not working

### ISSUE THREAD

**Issue by deorayyan** [Innologica/vue2-daterange-picker#217]
When singleDatePicker sets to "range" the endDate value same with startDate value on apply

**Comment by dejury** [comment]
Expecting same issue here. Could be fixed using 

`this.singleDatePicker && this.singleDatePicker !== 'range'`

in clickedApply() and onUpdateStartTime()

**Comment by dejury** [comment]
Well I see this is fixed in the dev branch, please create a new version and we are happy!

**Comment by dejury** [comment]
@deorayyan for now you can fix this using: `npm install Innologica/vue2-daterange-picker#master --save`

**Comment by nkostadinov** [comment]
Fixed in vue2-daterange-picker@0.6.2
