### ISSUE TITLE
Bootstrap dependancy? 

### ISSUE THREAD

**Issue by alexcroox** [Innologica/vue2-daterange-picker#218]
The README describes this library as having no dependancies, but the included CSS references classes that I believe are only part of bootstrap? Does it therefore have a dependancy on Bootstrap unless the user wants to try unravel what css is missing and fill them in themselves? Has anyone attempted this and can report their findings for others?

**Comment by alexcroox** [comment]
I will share my findings so far (not responsive), I'm using TailwindCss here:

```
<style lang="scss" scoped>
.vue-daterange-picker::v-deep .row {
  @apply flex;
}

.vue-daterange-picker::v-deep .col-md-auto {
  @apply flex-auto;
}

.vue-daterange-picker::v-deep .monthselect {
  @apply w-6/12;
}

.vue-daterange-picker::v-deep .yearselect {
  @apply w-5/12 pl-2;
}
</style>
```

**Comment by nkostadinov** [comment]
What do you want to achieve. You want to use it without including bootstrap ?

**Comment by alexcroox** [comment]
Yes, the README didn't indicate it had a bootstrap dependancy so I was confused for a while as to why the layout was wrong in my implementation until I started carefully comparing the markup styles with your demo page.

**Comment by alexcroox** [comment]
While the demo page does mention bootstrap it very clearly indicated "NO" dependancies so I didn't even consider it might have bootstrap, just saving other time and confusion with this thread here :)

![image](https://user-images.githubusercontent.com/1065835/99066361-c1b82d00-25a0-11eb-9b55-8cec3630aba6.png)

**Comment by nkostadinov** [comment]
Well it might be a bit confusing here really. I do not include other libs in package.json so this means no dependency. But I might be using a couple of CSS classes from bootstrap. I will add a task to myself to remove this bootstrap classes completely.

**Comment by sunnyboi21** [comment]
Any progress on the bootstrap removal?

**Comment by stevenschemers** [comment]
Also hoping for an update on the Bootstrap CSS dependency removal
