### ISSUE TITLE
Single date picker?

### ISSUE THREAD

**Issue by bpolaszek** [Innologica/vue2-daterange-picker#22]
Hey there,

The original jQuery component provides the option of having a single date picker instead of a range. This avoids requiring a different library for that use case while keeping the same CSS.

Do you plan to implement that feature?

Thank you!
Ben

**Comment by nkostadinov** [comment]
Hi, 
Yes I'm planning on releasing the calendar (picker) as a standalone component in this package. It needs a little work though :) but I cannot give you any date. I will keep this open until I do.

**Comment by bpolaszek** [comment]
Thank you @nkostadinov. 
I'd love to help but my JS skills aren't sufficient. 

You did a good work anyway.

Keep in touch,
Ben

**Comment by agronick** [comment]
Apparently this is resolved with the `singleDatePicker` option.

**Comment by nkostadinov** [comment]
as @agronick  said this option solves this issue. And for the future i am planning to make all components standalone to cover all possible cases.
