### ISSUE TITLE
Why is it that when I select a date, the default hour is 12?

### ISSUE THREAD

**Issue by zhnoah** [Innologica/vue2-daterange-picker#220]
Can it be set to change?

**Comment by nkostadinov** [comment]
It's 12:00 a.m. or 00:00 in 24h format

**Comment by zhnoah** [comment]
@nkostadinov Even if I set **timePicker24Hour:true**, the default hour is still 12.

![image](https://user-images.githubusercontent.com/7981230/100824490-34764300-3491-11eb-8995-75716e0a63b3.png)

**Comment by nashton109** [comment]
Had the same issue, the times always defaulted to 12 rather than 00, I managed to get it working by overriding the normalizeDateTime method;

`
   Vue.component("vue-date-range-picker",` DateRangePicker);

    const BaseDateRangePicker = Vue.options.components["vue-date-range-picker"]
    const CustomDateRangePicker = BaseDateRangePicker.extend({
        methods: {
            normalizeDatetime (value, oldValue) {
                let newDate = new Date(value);

                if (this.timePicker && oldValue) {
                    newDate.setHours(oldValue.getHours());
                    newDate.setMinutes(oldValue.getMinutes());
                    newDate.setSeconds(oldValue.getSeconds());
                    newDate.setMilliseconds(oldValue.getMilliseconds());
                } else {
                    newDate.setHours(0);
                    newDate.setMinutes(0);
                    newDate.setSeconds(0);
                    newDate.setMilliseconds(0);
                }

                return newDate;
            },
        },
    });
`

Then used;

`
components: {
    DateRangePicker: CustomDateRangePicker,
}
`

**Comment by JamesPoel** [comment]
Any update on this? still an issue.
