### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by attomius321** [Innologica/vue2-daterange-picker#222]
Is there a way to set placeholder ? Thank you

**Comment by nkostadinov** [comment]
the are some slots, but what do you mean by placeholder ?

**Comment by attomius321** [comment]
for the initial input, i need to place a placeholder like: 'Select dates'. Is there something like :placeholder="Select dates" ?

**Comment by nkostadinov** [comment]
There is input slot which you can override. There is a demo here, but this section is the new slots syntax but you can see how: 

https://innologica.github.io/vue2-daterange-picker/advanced/#slots-demo

You need something like <div slot="input">Select dates:</div>

**Comment by attomius321** [comment]
Out of curiosity, why didn't you created a props 'placeholder' for the input:
                    <input ref="yearSelect" type="number" :placeholder="placeholder" v-model="year" @blur="checkYear" class="yearselect col" />

props: {
 placeholder: ''
}

That's what i need and it seems that i can't achieve this with slots

**Comment by giannispan** [comment]
I struggled a bit with that. The only workaround i found is to use a filter like this.

```
<template #input="picker" style="min-width: 350px;">
      {{ picker.startDate | date }} - {{ picker.endDate | date }}
</template>
```
and then

```
filters: {
        date(val) {
            return val ? moment(val).format("DD/MM/Y") : "dd/mm/yyyy";  <- use this as a placeholder
        }
    }
```

**Comment by nkostadinov** [comment]
@giannispan that is not a workaround but the way it is intended to be used.

@attomius321 I didn't add placeholder prop because it's too specific. Everyone wants something different I cannot add all attributes so I made slots so you can override it how you want.
