### ISSUE TITLE
clear date button

### ISSUE THREAD

**Issue by tsulatsitamim** [Innologica/vue2-daterange-picker#223]
is there any feature to  clear date?

**Comment by nkostadinov** [comment]
you just set the value of startDate and endDate to null

**Comment by tsulatsitamim** [comment]
is there any integrated button to clear the date?

like this one

![2020-12-10_16-07](https://user-images.githubusercontent.com/5946791/101750710-f799f400-3b01-11eb-887a-66c3f0bbb0c7.png)
