### ISSUE TITLE
Disable Specific Days and Add Data Attribute

### ISSUE THREAD

**Issue by cagatay-unal** [Innologica/vue2-daterange-picker#227]
Hi,
How can I disable specific days ? For example: I want to disable this days; 22.01.2021, 12.02.2021, 05.06.2021, etc.
and I want to add html data-attribute to selected day ?

**Comment by nkostadinov** [comment]
you can disable specific dates if you look at this example - https://innologica.github.io/vue2-daterange-picker/advanced/#disabled-dates. But it is not possible to add data-attribute, why you need this ?

**Comment by cagatay-unal** [comment]
I want to add data-attribute, because I want to show price with days. If I can add price data to data-attribute I can use this attribute with css :before content

**Comment by nkostadinov** [comment]
yeah, I see. I'm planning to add date slot so you can customize it but haven't done it yet. Still wondering what is the best way to do it...

**Comment by cagatay-unal** [comment]
If you wanna you can create a new directive like :day-data :)

**Comment by nkostadinov** [comment]
I added a date cell slot so now you can override the date display and decorate it how you want.
