### ISSUE TITLE
togglePicker() - programmatically opening doesn't work

### ISSUE THREAD

**Issue by haayhappen** [Innologica/vue2-daterange-picker#228]
Hey there,

it seems that programmatically opening is not supported anymore? 

![image](https://user-images.githubusercontent.com/15108863/105699345-7b1f7100-5f07-11eb-8dd4-fa1842b854a9.png)

The image shows that I have the picker ref available. There is no bound togglePicker fn though.

Did the API change? Is there another way to toggle the picker programmatically?

Best regards

**Comment by Timibadass** [comment]
i'm also having issues opening the date picker using `this.$refs.picker.togglePicker(true);`. What's the solution to this problem?

**Comment by slav0nic** [comment]
if you using click event on button, you should do something like this:
`<Button @click.stop="onCalendarClick" />` 
looks like problem on `this.clickAway` method that binded to click event

**Comment by nkostadinov** [comment]
@slav0nic is right. The click on the button triggers the clickAway handler and closes the picker. You need to add .stop directive or manually stop the event propagation in the click handler - event.stopPropagation(). 
I will add a toggle button to the demo to illustrate this.
