### ISSUE TITLE
Single DateRangePicker Not Working

### ISSUE THREAD

**Issue by cagatay-unal** [Innologica/vue2-daterange-picker#229]
I defined single datepicker but it's doesn't select date

<date-range-picker
ref="picker"
opens="inline"
:single-date-picker="true"
v-model="dateRange"> </date-range-picker>

JS ==>

data: {

dateRange: {
startDate: null,
endDate: null
}
},

**Comment by nkostadinov** [comment]
there is a prop "single-date-picker" which should be what you are looking for.
