### ISSUE TITLE
Custom Date Range not working

### ISSUE THREAD

**Issue by ChupikNarik** [Innologica/vue2-daterange-picker#230]
```
date-range-picker(ref="picker"
	:locale-data="localeData"
	:date-range="dateRange"
	:ranges="ranges"
```

```
export default {
	components: {
		DateRangePicker
	},
	data(){
		return {
                    ranges: {
		        'Today': [moment().format('YYYY-MM-DD'), moment().format('YYYY-MM-DD')]
		    }
                }
     }
}
```

Render in calendar. But after click on custom element range dates on dateRange = null

```
dateRange:{
    endDate:null
    startDate:null
}
```

**Comment by vinidotdev** [comment]
I"m facing with the same problem.

**Comment by metalmini** [comment]
@ChupikNarik & @vinidotdev i also had this problem, but i found out that you need to create a Date object from your dates. So in you example it should be something like this:

`'Today': [new Date(moment().format('YYYY-MM-DD')), new Date(moment().format('YYYY-MM-DD'))]`

**Comment by nkostadinov** [comment]
@metalmini is right. The component requires a date object or date string in ISO format. If you need to use moment then do it like this:

`moment().toDate();`
