### ISSUE TITLE
Bug. Select range.

### ISSUE THREAD

**Issue by alekseymvt** [Innologica/vue2-daterange-picker#231]
* Open "daterange-picker"
![image](https://user-images.githubusercontent.com/22454101/106444642-12983d00-648f-11eb-89e6-40070d4569c7.png)

* Select **startDate**
![image](https://user-images.githubusercontent.com/22454101/106444821-4ecb9d80-648f-11eb-8c46-216d94a2ea90.png)

* Close "daterange-picker"
![image](https://user-images.githubusercontent.com/22454101/106444907-6d319900-648f-11eb-90b4-c334cc939418.png)

* Open "daterange-picker" again. I can't select **startDate** (14 january). "in_selection" is true.
![image](https://user-images.githubusercontent.com/22454101/106446230-0ca35b80-6491-11eb-8d2e-f14b88966e0d.png)

**Comment by nkostadinov** [comment]
10x for the PR :)
