### ISSUE TITLE
How to restrict range based on the start date

### ISSUE THREAD

**Issue by rahuldpi** [Innologica/vue2-daterange-picker#235]
I would like to limit the date range to a maximum of 1 year based on the start date. How can I achieve that?

**Comment by jakzaizzat** [comment]
Would love to know this too.

**Comment by nkostadinov** [comment]
I added startSelection and finishSelection events which are triggered when the user clicks the first or the last date. You can attach handlers there and change the max date.

**Comment by RaySantos92** [comment]
@startSelection and @finishSelection doens't fire, could you provide a example of a code with that??
