### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mwasigala** [Innologica/vue2-daterange-picker#239]
The picker doesn't toggle

**Comment by mojoblanco** [comment]
Do you mean it doesn't get displayed when you click on the input?

**Comment by mwasigala** [comment]
Yes

**Comment by xlaussel** [comment]
add the css file

**Comment by nkostadinov** [comment]
Yes, you need to include the css like this: 

`import 'vue2-daterange-picker/dist/vue2-daterange-picker.css'`

https://innologica.github.io/vue2-daterange-picker/#usage
