### ISSUE TITLE
Special Holidays

### ISSUE THREAD

**Issue by caglarevren** [Innologica/vue2-daterange-picker#240]
Hey man firstly thank you for this daterange picker,

I want to ask, is there a way to add, different background to a daterange-picker for special holidays in my country or the date i want. For exampla my birthday is 21th May and my friend is 1st April, i want to add red background  to this dates, on the daterange picker, is this possible?

Thank you for your answer, take care.

**Comment by nkostadinov** [comment]
Yes, look at this demo - https://innologica.github.io/vue2-daterange-picker/advanced/#disabled-dates

You can add props to classes object like this:
`classes['my-class'] = true`

This will add the class "my-class" to the date cell.  So you can style them with CSS.
