### ISSUE TITLE
Changing locale format results in broken rangeText in footer slot

### ISSUE THREAD

**Issue by metalmini** [Innologica/vue2-daterange-picker#244]
If you take a look at this example: https://codesandbox.io/s/vue2-daterange-picker-example-3tq8s?file=/src/App.vue

And change the 
`<date-range-picker v-model="pickerDates">`
to
`    <date-range-picker
      v-model="pickerDates"
      :locale-data="{ firstDay: 1, format: 'DD-MM-YYYY HH:mm:ss' }"
    >
`

The rangeText is showing something like this:
`DD-17-YYYY 14:04:21 - DD-17-YYYY 14:04:21`

Or am i missing something in the configuration? I mean, this should work... Right?

**Comment by nkostadinov** [comment]
That's because of wrong format. First part should be lowercase, like this:

`dd-mm-yyyy HH:mm:ss`

I saw the error in the docs, I will update them with next release.

**Comment by metalmini** [comment]
@nkostadinov the `HH` should also be lowercase and the `mm` of the minutes should be in caps.

Pretty annoying that the formatting differs from other standards. Maybe add a link to other docs to check the formatting, like this one https://blog.stevenlevithan.com/archives/date-time-format

**Comment by nkostadinov** [comment]
Yes, you are right. I added the link to the docs. The link that you provided actually is the library I use for formatting so this is the correct guide to the date format.
