### ISSUE TITLE
calendar panels get hidden behind Bootstrap Panel

### ISSUE THREAD

**Issue by ndethi** [Innologica/vue2-daterange-picker#245]
On clicking the date field, the calendar panels pops up below input as it should but it is hidden under the containing panel (Bootstrap Card) as shown below:

![vue2-dterangepicker-picker-hidden-underpanel-css](https://user-images.githubusercontent.com/26376298/115223408-6c1a1a80-a114-11eb-9c72-9088e08b6fe8.png)

**Comment by nkostadinov** [comment]
try appendToBody option or change the z-index with css.

**Comment by ndethi** [comment]
> 
> 
> try appendToBody option or change the z-index with css.

`:appendToBody="true"` in the picker template works. Thank you.
