### ISSUE TITLE
Could not use date-fns as date formatting source

### ISSUE THREAD

**Issue by arambert** [Innologica/vue2-daterange-picker#248]
I tried a lot of ways to use `date-fns` instead of `native` as dateUtil but I could not make it work.
Could you please post an example of a working implementation with date-fns?

Thanks!

**Comment by nkostadinov** [comment]
but why do you need to use date-fns for ? I removed support for date-fns util since native is better and can do everything I want without 3rd party libs. 
If you need help for date formatting, check this link https://blog.stevenlevithan.com/archives/date-time-format

**Comment by arambert** [comment]
I'm using date-fns for date formatting & utils everywhere in my app, I'd like to keep the same format syntax. Sadly the syntax of https://blog.stevenlevithan.com/archives/date-time-format is not the same as the one from date-fns...

**Comment by nkostadinov** [comment]
you could easily override the input slot and use you own formatting. I just wanted the extension to have minimum dependencies. May be I could add a callback function for formatting so everyone could use their own lib.

**Comment by arambert** [comment]
I've indeed overridden the input slot to use date-fns format.
It's just frustrating to see a dateUtil prop in the code but not to be able to use it ;)

**Comment by nkostadinov** [comment]
Yes, indeed there is such a prop. I should remove it :)

**Comment by nkostadinov** [comment]
The prop is removed from documentation.
