### ISSUE TITLE
Date range picker layout issue

### ISSUE THREAD

**Issue by ddulkevich-entrypoint** [Innologica/vue2-daterange-picker#255]
Looks like last update have broken range picker layout.
Problem with `flex-wrap` css property

[Image 1](https://i.imgur.com/sStotve.png)
[Image 2](https://i.imgur.com/E4M26ZG.png)

**Comment by warrence** [comment]
I manage to fix it with overriding the css class in my style.css as below

`.calendars {
    flex-wrap: nowrap !important
}`

**Comment by ghrapan** [comment]
Same here.

It seems that you have changed `class="calendars row no-gutters"` to `class="calendars"` as part of removing bootstrap dependency in #218, but left the `class="col-12 col-md-auto"` in `<calendar-ranges />`.

As a result, the layout is now boken in projects that uses Bootsrap.

**Comment by mitchkramez** [comment]
I'll be creating a pull request here shortly to remove those two classes, but @ghrapan is correct. If you're in a situation where you need a fix now before the next release or the pull request is merged, you can use the following css to override the bootstrap behavior with this `.ranges` element:

```
.ranges.col-12,
.range.col-md-auto {
        flex: auto;
        width: auto;
        max-width: inherit;
        position: static;
        padding-right:0;
        padding-left: 0;
}
```

**Comment by mitchkramez** [comment]
#268 awaiting approval and merge

**Comment by nkostadinov** [comment]
I merged it and will release later with the fix.
