### ISSUE TITLE
change-month emits only the first calendar date not the second

### ISSUE THREAD

**Issue by adi182** [Innologica/vue2-daterange-picker#256]
I'm using the change-month event with two calendars, thewy both emit the second parameter 0 or 1 correctly but always emit the date from the first / left calendar

from what I can see changing (on DateRangePicker.vue / changeRightMonth function)
        this.$emit('change-month', this.monthDate, 1)
to 
        this.$emit('change-month', this.nextMonthDate, 1)

**Comment by nkostadinov** [comment]
Thanks, I will fixed this.
