### ISSUE TITLE
@startSelection event doesn't fire

### ISSUE THREAD

**Issue by maharjanrams** [Innologica/vue2-daterange-picker#258]
@startSelection event doesn't fire when selecting start date.

**Comment by nkostadinov** [comment]
Cannot simulate rhis error - everything seems to be working fine.

**Comment by RaySantos92** [comment]
@startSelection is not firing

**Comment by RaySantos92** [comment]
> Cannot simulate rhis error - everything seems to be working fine.

@startSelection is not firing

`<date-range-picker
                ref="picker"
                class="date-picker"
                v-model="date_range"
                :minDays="5" 
                :maxDays="15"
                :auto-apply="true"
                :showDropdowns="true"
                @update="updateDates"
                :ranges="data_ranges"
            >
                <div slot="input" style="min-width: 350px;">
                    <span v-if="date_from && date_to !== null"
                        >{{ date_from }} - {{ date_to }}</span
                    >
                    <span v-else
                        >{{ date_range.startDate }} -
                        {{ date_range.endDate }}</span
                    >
                </div>
            </date-range-picker>`
            
`import DateRangePicker from "vue2-daterange-picker";
import moment from "moment";
const ReportExport = document.getElementById("ReportExport");

let today = new Date();
today.setHours(0, 0, 0, 0);

export default {
    components: {
        DateRangePicker
    },
    data() {
        return {
            stores: [],
            date_from: moment(
                moment()
                    .subtract(18, "months")
                    .toString()
            ).format("YYYY-MM-DD"),
            date_to: moment(moment().toString()).format("YYYY-MM-DD"),
            date_range: {
                startDate: moment(
                    moment()
                        .subtract(1, "months")
                        .toString()
                ).format("YYYY-MM-DD"),
                endDate: moment(moment().toString()).format("YYYY-MM-DD")
            },
            data_ranges: {
                "This month": [
                    new Date(today.getFullYear(), today.getMonth(), 1),
                    new Date(today.getFullYear(), today.getMonth() + 1, 0)
                ],
                "Last month": [
                    new Date(today.getFullYear(), today.getMonth() - 1, 1),
                    new Date(today.getFullYear(), today.getMonth(), 0)
                ],
                "Month before": [
                    new Date(today.getFullYear(), today.getMonth() - 2, 1),
                    new Date(today.getFullYear(), today.getMonth() - 1, 0)
                ]
            }
        };
    },
    created() {
        this.updateExportLink();
        this.retrieve();
    },
    computed: {
        sortedStores() {
            return this.stores;
            // return this.stores.sort((a, b) => (a.videos.length > b.videos.length ? -1 : 1));
        }
    },
    methods: {
        startSelect(){
            console.log(this.date_range);
        },
        updateDates() {
            this.date_to = moment(this.date_range.endDate).format("YYYY-MM-DD");
            this.date_from = moment(this.date_range.startDate).format(
                "YYYY-MM-DD"
            );
            this.updateExportLink();
            this.retrieve();
        },
        updateExportLink() {
            ReportExport.href =
                location.origin +
                "/report/videos-per-store-export?date_from=" +
                this.date_from +
                "&date_to=" +
                this.date_to;
        },
        retrieve() {
            axios
                .get("/report/videos-per-store-list", {
                    params: {
                        date_from: this.date_from,
                        date_to: this.date_to
                    }
                })
                .then(response => {
                    this.stores = response.data.stores;
                });
        }
    }
};`
