### ISSUE TITLE
I can't put two names the same for days of week (daysOfWeek)

### ISSUE THREAD

**Issue by jaquepaschoal** [Innologica/vue2-daterange-picker#263]
In the format I want to use, one letter a week is placed, and in Portuguese these letters are repeated for some of the days. In this case, the following error is given:

![image](https://user-images.githubusercontent.com/28562703/128230007-656dffa9-731c-416d-bca2-122658ecb758.png)

![image](https://user-images.githubusercontent.com/28562703/128230724-ef10ba7d-306d-494b-a968-3355aec05b31.png)

I believe that because you are using these strings as key, could there be another way to add these keys?

**Comment by nkostadinov** [comment]
hmm, yes, that is the reason. I never thought that someone will put 2 identical days :). I'll try to change to some other key
