### ISSUE TITLE
How to hide or disable ranks?

### ISSUE THREAD

**Issue by alexv96** [Innologica/vue2-daterange-picker#265]
I am using the library, the thing is that I try to disable some options but it does not let me hide it.

I would like to remove the options Today, Yesterday, This month, This year, Last month

```
                <date-range-picker
                    ref="picker"
                    :opens="opens"
                    :locale-data="{ firstDay: 1, format: 'dd-mm-yyyy' }"
                    autoApply="true"
                    :linkedCalendars="linkedCalendars"
                    ranges="null"
                    v-model="dateRange"
                ></date-range-picker>

data(){
      linkedCalendars: false,
      opens: 'center',
      dateRange: {
        startDate: null,
        endDate: null
      }
}
```
I would like to leave only the calendars.

![image](https://user-images.githubusercontent.com/33232796/129970518-79f71cd1-490a-4e75-bf20-e631e753c8fb.png)

**Comment by umutdr** [comment]
You can set ranges prop to false.

Here is the documentation: https://innologica.github.io/vue2-daterange-picker/#:~:text=a%20Date%20Object.-,ranges,-Object%2C%20Boolean
