### ISSUE TITLE
Improper alignment if I use inside table (Bootstrap 4)

### ISSUE THREAD

**Issue by rubanraj54** [Innologica/vue2-daterange-picker#27]
Hi, 

I would like to use your component inside table.

Basically I am trying to use the component to filter the rows based on date, So I've included your component in a column, so that based on users date range selection I can do the filtering.

But the alignment is not so good as you seen in the attached picture.

![screenshot from 2019-02-03 23-42-37](https://user-images.githubusercontent.com/10024405/52183986-fa44a780-280d-11e9-9091-fcc08faf757c.png)
 
I am using [vue-bootstrap4-table](https://github.com/rubanraj54/vue-bootstrap4-table) component to show list of user and I would like to use your component as a custom filter to filter the rows based on date range. It would be really great if you give a try to use the daterange-picker with bootstrap4 table and fix this. Let me know if you want a demo code.

Note : I am the author of [vue-bootstrap4-table](https://github.com/rubanraj54/vue-bootstrap4-table) plugin.

Cheers.

**Comment by nkostadinov** [comment]
may be there is some conflicting style from the table styles. If you could give me a js fiddle would make my life easier because I'm super busy lately.

**Comment by rubanraj54** [comment]
Hi @nkostadinov, I failed to make jsfiddle since there is no CDN support. But I tried to use your js & css file form dist folder but got an error in jsfiddle like below.

![screenshot from 2019-02-07 11-09-08](https://user-images.githubusercontent.com/10024405/52404252-d3fe6080-2ac8-11e9-81d8-645634e47565.png)

So I've a made sample vue project and made available in github for your use and the like is here (https://github.com/rubanraj54/vue2-daterangepicker-example).

Do git clone and run "npm install" and "npm run dev". You will see a sample page something like this.

![screenshot from 2019-02-07 11-12-06](https://user-images.githubusercontent.com/10024405/52404409-3c4d4200-2ac9-11e9-8405-e67a0d08e893.png)
And the respective code is here (https://github.com/rubanraj54/vue2-daterangepicker-example/blob/master/src/components/HelloWorld.vue)

**Comment by nkostadinov** [comment]
The problem comes from the padding that you apply to the table cells 

```
.table th, .table td {
    padding: 0.75rem; //this padding impacts the cells in the calendar which makes them big
    vertical-align: top;
    border-top: 1px solid #dee2e6;
}
```

**Comment by rubanraj54** [comment]
Actually, I am not applying any styles from my plugin. The padding is being applied by bootstrap itself. 

Since this plugin is based on bootstrap datarange picker, i thought it will work out of the box.

is it possible for you to fix this by your end?

**Comment by nkostadinov** [comment]
ok, I will add padding 0 to the cells and it will fix the problem

**Comment by rubanraj54** [comment]
Thanks a lot, if it works perfectly with bootstrap4 tables, then I will make my plugin in such a way that users can install your plugin to use as a date range filter.

**Comment by rubanraj54** [comment]
> The problem comes from the padding that you apply to the table cells
> 
> ```
> .table th, .table td {
>     padding: 0.75rem; //this padding impacts the cells in the calendar which makes them big
>     vertical-align: top;
>     border-top: 1px solid #dee2e6;
> }
> ```

And one more suggestion @nkostadinov , Please make <tr> & <th> backgroud-color as "white".

Because, if user apply "table-striped" class to bootstrap table, then it also applies the striped class to your calendar. 

![screenshot from 2019-02-09 13-23-15](https://user-images.githubusercontent.com/10024405/52520795-e8c82900-2c6d-11e9-9468-7fed58f6ad62.png)

If you do these two things, then it will solve this issue.

1. apply padding 0 only to your dateranger picker
```
.table.your-class th, .table.your-class td {
padding: 0px;
}
```
2. apply background color to "white"

```
.your-class tr, .your-class th {
background-color: white;
}
```

**Comment by nkostadinov** [comment]
I fixed the styles. Preparing a commit to the master with the fixes.
