### ISSUE TITLE
Single calendar with maxDate opens previous month

### ISSUE THREAD

**Issue by fedorovvldmr** [Innologica/vue2-daterange-picker#271]
1) set parameters as in the image
3) change maxDate to another day in same month (today, yesterday, tomorrow)
4) open the calendar - the previous month will be shown

![photo_2021-09-09_17-22-11](https://user-images.githubusercontent.com/3023645/132703741-58ebc41d-9b92-4d0e-b6fb-4ee0221fba6d.jpg)

**Comment by nkostadinov** [comment]
the problem is that the component in not designed to work with only one min/max date it requires 2 dates. I will look into it and try to fix it.
