### ISSUE TITLE
@startSelection and @finishSelection doens't fire, could anyone provide code usage with that?

### ISSUE THREAD

**Issue by RaySantos92** [Innologica/vue2-daterange-picker#277]

**Comment by nkostadinov** [comment]
I added event listeners to the demo page, they print the event with its params in the console.

**Comment by likol** [comment]
I have same issue too.
I'm pretty sure that is a bug.
according vue2 documents, `event names don’t provide any automatic case transformation` and `HTML’s case-insensitivity`
`so v-on:myEvent would become v-on:myevent – making myEvent impossible to listen to.`
[refer to vue2 document](https://vuejs.org/v2/guide/components-custom-events.html)

**Comment by nkostadinov** [comment]
I'll fix the names, but current demo page has working event handlers like this:

            @startSelection="logEvent('event: startSelection', $event)"
            @finishSelection="logEvent('event: finishSelection', $event)"

**Comment by likol** [comment]
@nkostadinov Yes, i notice it.
I don't why... my guess build process (Webpack pipeline) fixed the problem ?
it occur on browser directly included script `/dist/vue2-daterange-picker.umd.js` which issue we disscuss.

**Comment by AnjaliTonylijo** [comment]
@nkostadinov I am still not able to trigger the startSelection event, is it possible to call a custom method on emit.

**Comment by nkostadinov** [comment]
I refactored the event names so now it should be ok
