### ISSUE TITLE
How to disable auto changing start date on mouse hover.

### ISSUE THREAD

**Issue by imadarif** [Innologica/vue2-daterange-picker#285]
currently i am facing issue. first i select the date start date then i move mouse to previous date it automatically set the frirst date as end date and start date will be new date. i want to stop this feature on hover.

see booking.com or other airbnb calender. once user select the firstdate then if user move to previous date then it will not automatically change on hover. but when user click on previous date it will set previous date as start date.

**Comment by imadarif** [comment]
@nkostadinov

**Comment by nkostadinov** [comment]
that was the previous behavior that I recently "fixed"

**Comment by imadarif** [comment]
recently means? i just npm install in last two weeks

**Comment by imadarif** [comment]
can we make it like once user selected start date. after that if user select previous date by click then it will replace previous date with start date. so it will be nice.

**Comment by imadarif** [comment]
because right now its working fine but. if normal user select the 28 dec and then 3 jan 2022 and mistakenly move mouse up from previous date so it will change the date and look like abnormal behavior.

**Comment by nkostadinov** [comment]
recently means, 2 months ago :) . I wii see if I can add an option for that behavior.

**Comment by imadarif** [comment]
it will be a great if i get this fix asap other than that everything is perfect and good package (Y). for mobile and touch able device its fine but where mouse used it has this behavior.

**Comment by nkostadinov** [comment]
Your fastest solution is to use version 0.6.5, and I will add option in the next release so you can update.

**Comment by imadarif** [comment]
alright thanks let me try 0.6.5

**Comment by imadarif** [comment]
this is also exist in 0.6.5

**Comment by remievraere** [comment]
Hi, are you planing to merge this change soon ?
Thanks

**Comment by HansSchouten** [comment]
Can this be merged?

**Comment by HuuNghi** [comment]
@nkostadinov are you planing to deploy this change?
