### ISSUE TITLE
French Translation 

### ISSUE THREAD

**Issue by Xsmael** [Innologica/vue2-daterange-picker#287]
Hello, how can I have or add french translation in this module ?
To translate not only days and months names but also strings on the left like "Today", "Yesterday", "This Month"....

**Comment by nkostadinov** [comment]
Well, the day and month names are in locale prop and the ranges names you can translate by defining a new ranges array. See the docs for an example, ranges is just a prop to the picker, this is the default implementation: 

https://github.com/Innologica/vue2-daterange-picker/blob/master/src/components/DateRangePicker.vue#L323
