### ISSUE TITLE
clear the selected date

### ISSUE THREAD

**Issue by roy126** [Innologica/vue2-daterange-picker#289]
Hi, I can't clear the already selected date, I tried it like this:

this.date Range = { date Start: null, date End: null };

this.dateRange.date Start = null;
this.dateRange.date End= null;

this.dateRange.dateEnd= '';
this.dateRange.dateStart = '';

Nothing helps

![image](https://user-images.githubusercontent.com/48754971/149465822-12cb6db6-378f-4a0d-a906-079ab3d3b575.png)

**Comment by nkostadinov** [comment]
You are using wrong props for the v-model. They are startDate and endDate and you clear them like this: 
```
dateRange.startDate = null
dateRange.endDate = null
```
