### ISSUE TITLE
Does webpack require that you include the datepicker css?

### ISSUE THREAD

**Issue by RCady** [Innologica/vue2-daterange-picker#30]
I had an issue where the datepicker module was not showing on my application.

By adding the following line in my main entrypoint I was able to see the datepicker

`import 'vue2-daterange-picker/dist/lib/vue-daterange-picker.min.css'`

Is this a requirement when using Webpack or do was I missing something during install?

**Comment by jrran90** [comment]
thanks @RCady , took me 3 hours, this should be on the docs.

**Comment by nkostadinov** [comment]
I intentionally left this to be included separately if you want to use your own styles... may be I should add it to the docs
