### ISSUE TITLE
Missing previous and next chevrons next to current month

### ISSUE THREAD

**Issue by isaac-pawley** [Innologica/vue2-daterange-picker#31]
Your demo is missing the previous and next month chevrons: https://innologica.github.io/vue2-daterange-picker/ this might be the reason why it has disappeared on my app.

Love your version of date range picker btw, it's one of the best out there

**Comment by nkostadinov** [comment]
Hi, the reason is that I forgot to put size of the chevron elements and they are 0x0. As a quickfix you can use the following CSS:
```
.chevron-left, .chevron-right
{
    width: 16px;
    height: 16px;
    display: block;
}
```

I will fix it as soon as I find some free time because I'm really busy right now.

**Comment by isaac-pawley** [comment]
class fa-chevron-left and right fixes it

**Comment by nkostadinov** [comment]
This should be fixed now
