### ISSUE TITLE
How to Internationalization?

### ISSUE THREAD

**Issue by harundogan1** [Innologica/vue2-daterange-picker#315]
Hi. I'm using your daterange picker component. But when the web page is opened, the language comes in English. I don't want this. I want it to come according to what language is selected on the website. Is there a feature I can use for this? I want to say this. It would be nice if I define the language used on the website as a parameter for that feature and write the date according to the selected language when the page is opened. There is no problem when English is selected according to the current situation. However, even if the selected language is not English, the datepicker appears in English when the page is opened.
There is no problem when English is selected according to the current situation. However, even if the selected language is not English, the datepicker appears in English when the page is opened.

![image](https://user-images.githubusercontent.com/119854788/208861578-39ec56b2-8c51-49c6-b311-7b3bd2acd2b9.png)

**Comment by ala747** [comment]
Hi! You can always l10n/i18n as per your needs using the `locale-data` and `ranges` props which are fully documented at https://innologica.github.io/vue2-daterange-picker/#props

**Comment by harundogan1** [comment]
I have not seen an example of this. With which parameter should I send the current language on the website? Because I'm guessing it needs a keyword to work properly when I define it inside the objects you specify.

**Comment by ala747** [comment]
It's not automatic and there is no explicit example of this, you have to do it by yourself and the way to do it depends on the Internationalization method of your app. 

In my case, I use https://github.com/Polyconseil/vue-gettext so I can simply mark the `locale-data` and `ranges` single objects (with `this.$gettext('Whatever')` for example), then translate the strings normally as in the rest of my app, and finally everything goes as expected when a user changes the language. Actually, I also use MomentJS which allows me to set the days of the week and the months names automatically and already translated, for example:
```
{
  ...
  locale: {
    direction: 'ltr',
    format: 'dd/mm/yyyy',
    separator: ' - ',
    applyLabel: this.$gettext('Apply'),
    cancelLabel: this.$gettext('Cancel'),
    weekLabel: 'W',
    customRangeLabel: this.$gettext('Custom Range'),
    daysOfWeek: this.moment.weekdaysMin(),
    monthNames: this.moment.monthsShort()
  },
  ...
}
```
Other possible use case would be defining an object with the different locales and setting the calendar prop with the right locale, something like (Pseudo code alert):
```
{
  calendarLocales: {
    es: {
      format: 'dd/mm/yyyy',
      applyLabel: 'Aplicar',
      cancelLabel: 'Cancelar',
      customRangeLabel: 'Rangos Personalizados',
      daysOfWeek: ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sab'],
      monthNames: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic']
    },
    en: {
      format: 'mm/dd/yyyy',
      applyLabel: 'Apply',
      cancelLabel: 'Cancel',
      customRangeLabel: 'Custom Range',
      daysOfWeek: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
      monthNames: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
    }
  }
}
```
Then setting the `locale-data` prop to something like `:locale-data="calendarLocales[yourAppCurrentLang]"`. (In some cases you may need to use this way with computed properties to get it working properly.)

**Comment by nkostadinov** [comment]
@ala747 has explained it very nicely :). You just need to provide locale-data and ranges props. 

It is written with examples under the props description here - https://innologica.github.io/vue2-daterange-picker/#props
