### ISSUE TITLE
/deep/ selector

### ISSUE THREAD

**Issue by ifeelcream** [Innologica/vue2-daterange-picker#37]
Thanks for the previous fixes! Installing the new version, I had problems with the /deep/ selector in DateRangePicker.vue on line 451 & 490 (loader.js: Expected selector).

The /deep/ selector seems to be deprecated (https://developers.google.com/web/updates/2017/10/remove-shadow-piercing). I read about ::slotted() being an alternative (https://developer.mozilla.org/en-US/docs/Web/CSS/::slotted) although I am not savvy enough in CSS.

Thank you :)

**Comment by nkostadinov** [comment]
I believe that the deep selector in the link is different from the /deep/ in Vue scss. In vue /deep/ applies to child compoment and is processed by the loader. It is not used in the browser after the sources are built. do you have any issues with the styles ?

**Comment by ifeelcream** [comment]
Thanks for your answer, the problem seems to be that the sass-loader interprets the /deep/ as a selector and throws an error:

`ERROR in ./node_modules/vue2-daterange-picker/src/components/DateRangePicker.vue?vue&type=style&index=1&id=6e7dbc50&lang=scss&scoped=true& (./node_modules/css-loader!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-2!./node_modules/sass-loader/lib/loader.js??ref--7-3!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue2-daterange-picker/src/components/DateRangePicker.vue?vue&type=style&index=1&id=6e7dbc50&lang=scss&scoped=true&)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

                    /deep/ ul {
               ^
      Expected selector.
    ╷
451 │                 /deep/ ul{
    │                 ^
    ╵
  stdin 451:17  root stylesheet
      in C:\laragon\www\network-asset-management\node_modules\vue2-daterange-picker\src\components\DateRangePicker.vue (line 451, column 17)
 @ ./node_modules/vue2-daterange-picker/src/components/DateRangePicker.vue?vue&type=style&index=1&id=6e7dbc50&lang=scss&scoped=true& (./node_modules/style-loader!./node_modules/css-loader!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-2!./node_modules/sass-loader/lib/loader.js??ref--7-3!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue2-daterange-picker/src/components/DateRangePicker.vue?vue&type=style&index=1&id=6e7dbc50&lang=scss&scoped=true&) 2:14-331
 @ ./node_modules/vue2-daterange-picker/src/components/DateRangePicker.vue?vue&type=style&index=1&id=6e7dbc50&lang=scss&scoped=true&
 @ ./node_modules/vue2-daterange-picker/src/components/DateRangePicker.vue
 @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/assets/js/views/Reporting.vue?vue&type=script&lang=js&
 @ ./resources/assets/js/views/Reporting.vue?vue&type=script&lang=js&
 @ ./resources/assets/js/views/Reporting.vue
 @ ./resources/assets/js/router.js
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss`

**Comment by nkostadinov** [comment]
Hmm, can you provide a list of npm packages and versions for vue & the loaders, the result of : 

`npm list --depth=0 | grep "vue\|sass"`

**Comment by ifeelcream** [comment]
Here is the output:
```
├── @fortawesome/vue-fontawesome@0.1.5
├── bootstrap-vue@2.0.0-rc.15
├── node-sass@4.11.0
├── sass@1.17.3
├── sass-loader@7.1.0
├── vue@2.6.9
├── vue-content-loader@0.2.1
├── UNMET DEPENDENCY vue-password-strength-meter@1.4.2
├── vue-router@3.0.2
├── vue-tables-2@1.4.70
├── vue-template-compiler@2.6.9
├── vue-tippy@2.1.2
├── vue-toasted@1.1.26
├─┬ UNMET DEPENDENCY vue2-daterange-picker@0.2.0
│ ├── vue@2.6.9
│ └── vue-clickaway@2.2.2
```

I am developing onWindows, which seems to be the problem. It has no problems compiling on Ubuntu. The output in Windows is the same, so same plugins are installed. I only got this problem with the new version though.

**Comment by nkostadinov** [comment]
I will try to simulate it here on my PC. I'm developing on windows too so I guess this is not the problem :)

**Comment by ifeelcream** [comment]
You are right, I just removed the node_modules folder and cleaned the cache and now it is also not working with Ubuntu when compiling again. Thank you for your help so far! :)

**Comment by nkostadinov** [comment]
Just a shot in the dark here, but could you remove sass from you dependencies, delete node_modules and try again. They removed the /deep/ selector in sass and you are using the latest versions which is causing the problem.

**Comment by ifeelcream** [comment]
First there was an error, complaining about missing sass. I added the following to the webpack.mis.js:

```
.sass('resources/assets/sass/app.scss', 'public/css', { implementation: require('node-sass') })
```

The implementation part in connection with removing sass seems to have solved the problem.

**Comment by nkostadinov** [comment]
I will still remove /deep/ selector in favor of ::v-deep so devs with newer versions of sass wont have any problem.
