### ISSUE TITLE
Week numbers

### ISSUE THREAD

**Issue by omsiqveland** [Innologica/vue2-daterange-picker#38]
Could you add an option which, when set, makes the calendar(s) show week numbers?

**Comment by nkostadinov** [comment]
here you go :)

**Comment by omsiqveland** [comment]
Nice! Thanks!

Would be great if I also could change the default 'W' label, to my own locale.
Maybe this is what the prop 'locale.weekLabel' for is intended for?
It is currently hardcoded to W.

**Comment by nkostadinov** [comment]
Well, actually yes. I forgot it :) We'll fix it now.

**Comment by nkostadinov** [comment]
It should be ok now.
