### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by valeriy-efimov** [Innologica/vue2-daterange-picker#39]
I try add your plagin to my project
![image](https://user-images.githubusercontent.com/5989188/54819487-aea66a00-4ca4-11e9-87a3-1b15fa4c18fa.png)
I use admin lte theme and laravel 5
when i try to open picker they dont show
but in code the is present
![image](https://user-images.githubusercontent.com/5989188/54819536-dd244500-4ca4-11e9-9461-70f6aa10e699.png)

upd
i found problem in https://github.com/Innologica/vue2-daterange-picker/issues/30
write about it in the documentation. I also spent 2 hours on this ...

![image](https://user-images.githubusercontent.com/5989188/54820014-6720dd80-4ca6-11e9-8b90-217180b9a67b.png)
but it still shows crooked

solutions
```

<date-range-picker
                class="date-vue-picker"
                        ...

    .date-vue-picker .row{
        margin: 0 !important;
    }
```

**Comment by nkostadinov** [comment]
Can you try to import the CSS like this:

`import 'vue2-daterange-picker/dist/lib/vue-daterange-picker.min.css'`
