### ISSUE TITLE
Documentation Typo

### ISSUE THREAD

**Issue by purplelady105** [Innologica/vue2-daterange-picker#4]
I was trying to test out this package, but I noticed that in the Documentation, the following line is referring to the wrong path:

`import DateRangePicker from 'vue-daterange-picker/src/components/DateRangePicker'`

It should be:

`import DateRangePicker from 'vue2-daterange-picker/src/components/DateRangePicker'`

And when using the component, it needs to have the closing `</date-range-picker>` tag in order to render.

**Comment by nkostadinov** [comment]
10x. I fixed the documentation.
