### ISSUE TITLE
getMonth is not a function

### ISSUE THREAD

**Issue by FireflyDesign** [Innologica/vue2-daterange-picker#40]
Hello :)

I tried to use the newest version (2.3) of vue2-daterange-picker and found a bug:
When I try to change second calendar month I receive an error: **"TypeError: t.getMonth is not a function"**

Screen: http://prntscr.com/n45skn

**Comment by nkostadinov** [comment]
i've commited the fix in the master branch, i'm fixing another issue and then will release minor update

**Comment by iamqinglong** [comment]
I'm getting this error too. How to fix ?

**Comment by FireflyDesign** [comment]
npm update vue2-daterange-picker

**Comment by nkostadinov** [comment]
Yes, you should update to the latest version and it should be fixes there

**Comment by paomian567** [comment]
Updated to the latest version，getMonth is not a function, error
