### ISSUE TITLE
Cleared state / null value?

### ISSUE THREAD

**Issue by AlanVerne** [Innologica/vue2-daterange-picker#41]
Tying to use 'null' value to get 'nothing selected' behavior. Is there a supported way to do it? Thank you.

**Comment by nkostadinov** [comment]
Currently the component doesnt support null values, but I'm thinking to add this functionality

**Comment by dacoto** [comment]
Is there a date to add this functionality?
Thank you.

**Comment by nkostadinov** [comment]
Actually i'm working on this right now in feature/single-components branch. But I tried to do many things at once and things got messy. So I will start with new branch just with this functionality. 

About the date - I cannot give you estimate sorry :)

**Comment by nkostadinov** [comment]
I think I'm done with the null value functionality. Could you test it and confirm it is working properly. 

You can use "vue2-daterange-picker#feature/null_values" to get the null value branch.

If it's ok I will merge and release it.

**Comment by nkostadinov** [comment]
just released v0.2.4 which should solve this issue
