### ISSUE TITLE
Show dropdowns - minYear and maxYear

### ISSUE THREAD

**Issue by CodeShotPL** [Innologica/vue2-daterange-picker#43]
Hello :)

Is it possible to use daterangepicker minYear and maxYear props?
Years dropdown has always only 20 options :<

Greetings!

**Comment by CodeShotPL** [comment]
Up ^^

**Comment by nkostadinov** [comment]
just released v0.2.4 which should solve this issue. The years are no longer a dropdown but an input type number. You can select any year but within the range of min/max date (if provided)

**Comment by chhumsina** [comment]
> Hello :)
> 
> Is it possible to use daterangepicker minYear and maxYear props?
> Years dropdown has always only 20 options :<
> 
> Greetings!

I really want this also.
