### ISSUE TITLE
maxDate prop does not affect timepicker

### ISSUE THREAD

**Issue by CodeShotPL** [Innologica/vue2-daterange-picker#44]
Hello :)

I use daterangepicker with :timepicker enabled.
I tried to restrict dates with :maxDate prop (date was: 2019-04-17T15:29:03). 
It works great with dates, but doesn't work with time. I mean, I still could choose date like 2019-04-17T12:00:00 ☹️

Thank you! 🙂

**Comment by nkostadinov** [comment]
yes, the time is not considered since it's a date picker :) But I will fix it
