### ISSUE TITLE
Compatibility with Quasar Framework

### ISSUE THREAD

**Issue by diegomagikal** [Innologica/vue2-daterange-picker#47]
First of all, thanks for this great project!

I'm trying to run the same readme code example in a Quasar Framework project (vue based):
https://codesandbox.io/s/w7046xvvnk
But I'm a bit confusing with two things:

1.  Why ```startDate``` and ```endDate```  data values doesn't changes when I click on Apply? These properties aren't reactive? Or it is a compatibility issue with Quasar?
2. How to use ```@update``` event? The ```@update="console.log(value)"```in the readme is broken. I'am trying to use a custom method, but the parameter is always ```undefined```
3. Based on question 1, if I use ```singleDatePicker```, what is the the v-model name? startDate? endDate? Both are equals?

thanks.

**Comment by nkostadinov** [comment]
Hi, 
I've made some changes about the way the component uses the start/end date and I need to update the demo. The component now uses v-model attribute for two way data binding. You need to pass and object with startDate and endDate as properties in it and it should work just fine. This way when you click apply this var will hold the new values (it is reactive).

If you want to hook to the update event you should do it without adding params to the function e.g. : 
@update="update_message" and it should work.

I've updated your demo, you can check it here: 
https://codesandbox.io/s/52vw8zpvqx?fontsize=14

**Comment by diegomagikal** [comment]
It works now, thanks!
