### ISSUE TITLE
Vulnerability from dependencies

### ISSUE THREAD

**Issue by MounirOnGithub** [Innologica/vue2-daterange-picker#49]
I've tried to clone the project, for reviewing a pull request in the project and found a lot of vulnerabilities from dependencies : 
![Screenshot](https://user-images.githubusercontent.com/15196051/56587206-6d75e280-65e1-11e9-8876-3407ff1d0c64.png)

**Comment by nkostadinov** [comment]
These are from dev dependcies which I cannot remove them all currently. You don't need to worry they are no present in the component as it doesnt use them. They are mostly for development and testing.

**Comment by MounirOnGithub** [comment]
OK do you manage to update it ?
