### ISSUE TITLE
Remove bootstrap dependency

### ISSUE THREAD

**Issue by brandoncordell** [Innologica/vue2-daterange-picker#50]
Are there any plans to move away from bootstrap like the original daterangepicker library has? If not, would you be open to a PR removing the dependency?

**Comment by nkostadinov** [comment]
I currently dont have such plans. Bootstrap is not actually a dependancy but i've used some bootstrap styles in the component. No css is included by default so you can include your custom css - at least that was the idea.
How do you plan to remove the dependency ?

**Comment by agronick** [comment]
I don't use bootstrap. I just had to add a few classes myself.

**Comment by nkostadinov** [comment]
As I don't plan to remove bootstrap anytime soon i'm closing this issue. If you have other ideas suggestions and PRs are welcome.
