### ISSUE TITLE
TypeError: t.getMonth is not a function

### ISSUE THREAD

**Issue by paomian567** [Innologica/vue2-daterange-picker#51]
我已经更新到最新版了，可以还是报错，不知道是为什么，
https://github.com/Innologica/vue2-daterange-picker/issues/40
一样的错误，一样的问题

**Comment by nkostadinov** [comment]
could you be more specific how you get that error and please write in english. What params you pass and how do you pass them ? If you could create a fiddle it would be nice

**Comment by nkostadinov** [comment]
just released v0.2.4 which should solve this issue.
