### ISSUE TITLE
CSS doesn't look good, UI cuts off and many console errors

### ISSUE THREAD

**Issue by timothymarois** [Innologica/vue2-daterange-picker#52]
It looks like the UI goes off screen, the css of the calendar is bad, and in the examples you mentioned using `moment()` but you can not directly call `moment` from vue, you must call it through a wrapper or global scope otherwise it's looking for the specific method within the component, that needs to be more clear. 

Test running this straight out of the box, there are a lot of errors, the current state of this package is not close to production. 

As you can see, CSS is messed up on days, and the alignment is cutting off screen.

![Screenshot 2019-04-26 13 28 45](https://user-images.githubusercontent.com/2489333/56825598-a2737680-6827-11e9-9e46-113b69b12467.png)

Console errors I'm getting after copying the details from demos on documentation. 

![Screenshot 2019-04-26 13 32 34](https://user-images.githubusercontent.com/2489333/56825643-c1720880-6827-11e9-8993-051669d9c22b.png)

**Comment by agronick** [comment]
I don't get any of these errors. CSS can be solved by adding bootstrap or adding the CSS yourself. I looks like you're missing moment or setting something else wrong and your data properties never got set.

**Comment by nkostadinov** [comment]
Ok, can you provide sample code on a js fiddle or something similar ? Did you include the CSS as mentioned in the docs: 
```
//you need to import the CSS manually (in case you want to override it)
import 'vue2-daterange-picker/dist/lib/vue-daterange-picker.min.css'
```
There is also a dependancy for moment js which seems is not satisfied by your packages. I'm not calling it directly, I am importing it in every component I'm using it.

**Comment by jonnylink** [comment]
Yeah, while the CSS isn't great, these errors seem to be of his own making.
