### ISSUE TITLE
Prop to disable specific date - isInvalidDate function

### ISSUE THREAD

**Issue by bahung1221** [Innologica/vue2-daterange-picker#54]
Hello everyone,

I see that option on http://www.daterangepicker.com/,
so can i have the same option on this vue version?
it will allow me add some specific rules to disable specific dates,
**example**: disable all weekend date

Thank you very much!

![image](https://i.imgur.com/2fGPybb.png)

**Comment by nkostadinov** [comment]
Hi, I've already considered such a function so I will implement this :) . Just cannot give you estimation at this time because I've already started with other functionalities which I wanna finish first.

**Comment by nkostadinov** [comment]
I added dateFormat prop which accepts function as param. The function has 2 arguments classes and date. You can check the demo how I used that to disable specific date.
