### ISSUE TITLE
Calendar popup trapped inside container (cutoff)

### ISSUE THREAD

**Issue by jonnylink** [Innologica/vue2-daterange-picker#57]
A pretty common use case would be to have a container or widget of some sort that has the form inside it. Unfortunately, the calendar popup doesn't popup all the way like it should, as seen below.

<img width="509" alt="Screen Shot 2019-05-05 at 11 30 17" src="https://user-images.githubusercontent.com/20388240/57196388-73958880-6f2a-11e9-8802-fcd1bfea1aac.png">

This actually can't be fixed by adding style because it's part of the scoped style (which becomes inline). Position relative is the source of the trouble in [DateRangePicker.vue](https://github.com/Innologica/vue2-daterange-picker/blob/e78fbd8c1032fbfe143698ccd1549745aada29f2/src/components/DateRangePicker.vue#L568).

```    .
vue-daterange-picker {
    position: relative;
    display: inline-block;
}
```

If you'd like I can try to fix this and send a PR.

**Comment by nkostadinov** [comment]
Hi, if you think only this relative position is the trouble you could make a PR, I will merge it.

**Comment by nkostadinov** [comment]
I cannot remove the relative position because the calendar uses position absolute and this is needed. Are you sure this is not on your side - may be some overflow: hidden. 
If not could you provide an example somewhere so I can test and work around this. 10x

**Comment by sec0ndhand** [comment]
This is a problem for me as well.  Other libraries attach to a node somewhere else to the dom rather than the parent.  Using popperjs or something like that, this can be achieved.  Would this be welcomed in a pull request @nkostadinov ?

**Comment by nkostadinov** [comment]
I try very hard to keep my dependencies to minimum. I would welcome non dependent PR :) . I dont even use a date/time library.  I may try to attach the dropdown to another element though - may be an option would suffice.

**Comment by sec0ndhand** [comment]
@nkostadinov buefy has a `attach-to-body` attribute that creates a dom-element on body: 
```
export function createAbsoluteElement(el) {
    const root = document.createElement('div')
    root.style.position = 'absolute'
    root.style.left = '0px'
    root.style.top = '0px'
    const wrapper = document.createElement('div')
    wrapper.appendChild(el)
    el.appendChild(el)
    document.body.appendChild(root)
    return el
}
```

And they update the position once activated using the `updateAppendToBody` [here](https://github.com/buefy/buefy/blob/dev/src/components/dropdown/Dropdown.vue#L277), so it's more intensive calculation but this method will 'jailbreak' the datepicker from `overflow: auto` elements.

**Comment by bohnman** [comment]
@nkostadinov @sec0ndhand 

vue-select has an interesting approach.  Like buefy, it has an append-to-body prop.  However, vue-select makes no attempt to actually position the "dropdown".  Rather, it accepts a calculate-position function as a prop for library users to implement the positioning (eg. with Popper.js).


[Link to relevant vue-select documentation and example](https://vue-select.org/guide/positioning.html#popper-js-integration)

**Comment by nkostadinov** [comment]
@bohnman that's an interesting approach. I'll take a look into it.
