### ISSUE TITLE
any possible way to keep calendar open all the the time? 

### ISSUE THREAD

**Issue by rasponline** [Innologica/vue2-daterange-picker#58]
I'm looking for an option using which I can keep the calendar open all the time as soon as page/component loads/render.

User don't need to click on input box every time to select the date range.

Is there any possible way?

**Comment by nkostadinov** [comment]
just released v0.2.4 which should solve this issue. it is not documented yet. The picker emits an event "toggle" with 2 parameters:

1. the boolean value whether the picker is open - true/false
2. toggle function which you can call to open/close the picker

e.g.: 
`
....
@toggle=checkOpen
....

      checkOpen (open, toggle) {
        //calling this will keep it open
       toggle(true) //true/false means to open/close
      }
`
