### ISSUE TITLE
Close or Hide Event Handlers

### ISSUE THREAD

**Issue by arbiasgjoshi** [Innologica/vue2-daterange-picker#59]
Does the component support any 

`onClose ` or  `hide `

event handlers. I have some scenarios where I need to detect when the plugin is closed so I can trigger a specific function and animation but I found no workaround about it.

**Comment by nkostadinov** [comment]
No it currently doesnt support them but will surely add them

**Comment by nkostadinov** [comment]
there is an event called "toggle" which has 2 params (open, toggle). The open is (true/false) which shows if the picker is open/closed. The toggle is function which accepts true/false param to control open/closed state of the picker.
