### ISSUE TITLE
module not found issue when hard refresh done

### ISSUE THREAD

**Issue by sudhir600** [Innologica/vue2-daterange-picker#6]
Hi
I found a serious issue. I have a page called sales. in this page, I initialize date picker as described on the doc.  Even its working file but only if I am navigating from home URL to sale page then datePicker is working buf if I refresh this page (hard refresh), then I am getting an error. 

`Cannot find module 'vue2-daterange-picker/src/components/DateRangePicker' from 'C:\development\workspace\project'`
![image](https://user-images.githubusercontent.com/4952560/42220526-d8050270-7eec-11e8-9aa5-3b2c3db9165a.png)

Here is the code-
```
<script>
import { VueGoodTable } from 'vue-good-table';
import DateRangePicker from 'vue2-daterange-picker/src/components/DateRangePicker'

export default {
	components: {
	  VueGoodTable, DateRangePicker
	},
..

```

And in view

```
<template>
  <date-range-picker class="dateRange" :startDate="startDate" :endDate="endDate" v-model="dateRange" @input="console.log(value)"></date-range-picker>
</template>

```

**Comment by nkostadinov** [comment]
Hm, that's really strange. I don't think it is related to the component itself but will try to simulate the issue in a nuxt project here.

**Comment by otono** [comment]
Have the same issue on nuxt. Aftr refresh getting "SyntaxError Unexpected identifier"
![Screenshot from 2019-07-30 11-15-56](https://user-images.githubusercontent.com/195792/62112462-6edb3900-b2bb-11e9-8863-f40c53134c0f.png)
