### ISSUE TITLE
Can't set minDate and maxiDate  with vue

### ISSUE THREAD

**Issue by minnummt** [Innologica/vue2-daterange-picker#63]
minDate and maxiDate  declared inside dateRange property like:
       dateRange: { // used for v-model prop
                 startDate:'2019-05-01',
                 endDate: '2019-05-15',
                 minDate:'2019-01-01',
                 maxDate:'2019-07-31',
            },
            opens: "left",
            locale: {
                direction: 'ltr', 
                format: 'YYYY-MM-DD', 
                separator: ' - ', 
                applyLabel: 'Apply',
                cancelLabel: 'Cancel',
                weekLabel: 'W',
                customRangeLabel: 'Custom Range',
                daysOfWeek: moment.weekdaysMin(), 
                monthNames: moment.monthsShort(), 
                firstDay: 1, 
                showWeekNumbers: true,
            },
but this minDate and maxDate does not reflect on date-range-picker calendar. Still dates between minDate and maxDate are able to select.

**Comment by nkostadinov** [comment]
The minDate and maxDate props are not inside the dateRange object
