### ISSUE TITLE
Select year from dropdown

### ISSUE THREAD

**Issue by banisirohi** [Innologica/vue2-daterange-picker#64]
I can't select year past 2007 on your demo even if I set mind date to 1984-09-02. Does it not allow year past 2007?

**Comment by nkostadinov** [comment]
Yes it allows but the dropdown shows only +/-10 years. I'm gonna push changes allowing you to set the years, and will also respect the max dates properties

**Comment by nkostadinov** [comment]
I removed the dropdown in favor of input [type=number] :)

Also now the input respects the min/max date and you cannot select something out of scope

**Comment by peiledoir** [comment]
What's the best way to override the input[type="number"] for Years to be a dropdown for a selected range of years?

The UX breaks when trying to backspace the last two digits and would be much easier to use as a dropdown.

**Comment by chhumsina** [comment]
> What's the best way to override the input[type="number"] for Years to be a dropdown for a selected range of years?
> 
> The UX breaks when trying to backspace the last two digits and would be much easier to use as a dropdown.

I want to have Dropdown year selection too. :)
