### ISSUE TITLE
This dependency was not found:  * Vue

### ISSUE THREAD

**Issue by damonjanis** [Innologica/vue2-daterange-picker#68]
Is there some extra configuration required to get vue2-daterange-picker to compile with webpack? I get this error when it compiles:

This dependency was not found: in ./node_modules/vue2-daterange-picker/dist/lib/vue-daterange-p.min.js
To install it, you can run: npm install --save Vue

Vue is already installed so confused on this one.

**Comment by nkostadinov** [comment]
I removed the vue and moment libs from the bundle and this is causing the problem. Seems the same as #66 . I merged the pull request so now it should be fine. 

Is it possible to test it from the master branch if it is ok with you now.

**Comment by damonjanis** [comment]
Thanks @nkostadinov for looking at it. That does partially solve it, but there is still a compile issue. vue-daterange-picker-min.js script is referring to 'Vue' in several places and should be referring to 'vue'. If all Vue occurrences in that script file are replaced with vue I think it will compile correctly.

**Comment by nkostadinov** [comment]
I just bumped the version to 0.2.5 and recompiled the lib. I think it should be ok now

**Comment by damonjanis** [comment]
That works perfectly, thanks for putting this component together!
