### ISSUE TITLE
Linked Calendars

### ISSUE THREAD

**Issue by steveWinter** [Innologica/vue2-daterange-picker#69]
In the original picker it was possible to 'unlink' the two calendars which allowed a range of > 62 days to be selected using `"linkedCalendars": false`.

Has this feature been ported across to this version? If so, how is that configured? If not is it likely to be?

**Comment by nkostadinov** [comment]
you can now select any range not just 62 days. This functionality is not developed yet, but I may add it in next release.

**Comment by steveWinter** [comment]
Thanks so much, that's great news - do you have a feeling for when this might be deployed?

**Comment by nkostadinov** [comment]
I released new vesion which has this prop and should work as expected.
