### ISSUE TITLE
Show calendar only with custom range date

### ISSUE THREAD

**Issue by mouadhkaabachi** [Innologica/vue2-daterange-picker#72]
Hi,
thank you for Vue date-picker project, I would like to use it in my project,
I wanted to know if there is a way to display the calendar only if you select custom range label from a dropdown list like this:
http://www.daterangepicker.com/#example4  (Predefined Date Ranges)

![image](https://user-images.githubusercontent.com/1279660/59931843-2de33f80-9446-11e9-95ba-80a9641e7cbe.png)
and when you select custom range 
![image](https://user-images.githubusercontent.com/1279660/59933265-689aa700-9449-11e9-9529-ba9b16b7c61e.png)

thx

**Comment by nkostadinov** [comment]
currently there is no such option, but I will add it in the next version

**Comment by fvdung** [comment]
Can add range options (e.g `this week`, `last 7 days`) and add multiple language option?

**Comment by nkostadinov** [comment]
I've added this function in the latest version 0.4
