### ISSUE TITLE
Module parse failed: Unexpected token (46:12)

### ISSUE THREAD

**Issue by yehudahkay** [Innologica/vue2-daterange-picker#73]
Hi thanks this looks cool, i get the following issue in my build

ERROR in ./node_modules/vue2-daterange-picker/src/components/util.js
Module parse failed: Unexpected token (46:12)
You may need an appropriate loader to handle this file type.
|     }
|
|     return {...default_locale, ...options }
| }
|

**Comment by nkostadinov** [comment]
seems you are missing the spread operator polyfill.

**Comment by yehudahkay** [comment]
What do I need to do?

**Comment by nkostadinov** [comment]
could you try to add to your dependencies:

`"core-js": "^2.6.5",`

If this works for you I will add it to the components dependcies.

**Comment by yehudahkay** [comment]
No, I actually tried that before with version 3 now I tried with 2 as well

**Comment by marcelinhov2** [comment]
I got the exact same thing. Did you handle it? 

Thanks.

**Comment by nkostadinov** [comment]
I'm trying to reproduce this error without success for now. Are using this in the browser or in webpack project ? 
Do you have .babelrc or babel.config.js in your projects with   preset: 
`[ '@vue/app'  ] `
in it

**Comment by yehudahkay** [comment]
I imagine it's related to webpack somehow. I am using laravel mix (a webpack wrapper) version 3

**Comment by nkostadinov** [comment]
The solution for laravel mix (I used that before) is 

`npm install --save-dev babel-plugin-transform-object-rest-spread
`

and than create a .babelrc file in your project directory

```
{
  "plugins": ["transform-object-rest-spread"]
}
```
I just want to make it work out of the box for all scenarios.

**Comment by mwmasterweaks** [comment]
![image](https://user-images.githubusercontent.com/52690683/60862128-3eb9f080-a24f-11e9-966c-578ef0b33961.png)

same problem here 

.babelrc

{
  "plugins": ["transform-object-rest-spread"],
  "presets": [["env", { "modules": false }], "stage-3"]
}

**Comment by nkostadinov** [comment]
@mwmasterweaks are you also using laravel mix ?

**Comment by mwmasterweaks** [comment]
I have no idea about laravel mix but all I know is I use webpack

**Comment by nkostadinov** [comment]
could you share you dependencies in package.json

**Comment by mwmasterweaks** [comment]
![image](https://user-images.githubusercontent.com/52690683/60868251-37024800-a25f-11e9-9ddc-984a9bf59b5a.png)

**Comment by rpaggi** [comment]
> I imagine it's related to webpack somehow. I am using laravel mix (a webpack wrapper) version 3

Same problem here, I'm using Laravel Mix too.



> The solution for laravel mix (I used that before) is
> 
> `npm install --save-dev babel-plugin-transform-object-rest-spread `
> 
> and than create a .babelrc file in your project directory
> 
> ```
> {
>   "plugins": ["transform-object-rest-spread"]
> }
> ```
> 
> I just want to make it work out of the box for all scenarios.

I've tried that, but doesn't work...

**Comment by kot-begemot** [comment]
Same thing here =(

**Comment by rogersxd** [comment]
Hi, i'm using laravel-mix + webpack to transpiling my files. My `app.js` broken on safari browser =< version 11. I try to change the line 46, like @kot-begemot suggested. I try set `@babel/env`, `@vue/app` and others presets and plugins on `.babelrc.` But doesn't work.

**Comment by DelfsEngineering** [comment]
Has this beed addressed? 
It would suck to trans-pile to a low code base just for this one module on one crappy browser.

**Comment by rogersxd** [comment]
@DelfsEngineering I solved the problem by transpiling the files correctly. Safari version 11 is not that old and deserves some attention.

**Comment by DelfsEngineering** [comment]
> @DelfsEngineering I solved the problem by transpiling the files correctly. Safari version 11 is not that old and deserves some attention.

What Babel settings worked? I am not having a ton of luck. Thanks for the udpate.

**Comment by nkostadinov** [comment]
In the last version I think I fixed the older browser problem by including the dist files.  What version of the package are you using ?

@DelfsEngineering if you are using an older version you can add this to vue.config.js :
```
module.exports = {
  transpileDependencies: [
    'vue2-daterange-picker',
  ],
.....
```
