### ISSUE TITLE
Can't setup...

### ISSUE THREAD

**Issue by magorizer** [Innologica/vue2-daterange-picker#76]
Hi, 
I like your plugin very much, I have been searching for days, and yours seems the best, but...
I just couldn't set it up to work, and I've been trying for ages. Every other plugin has a proper example, but yours :)
I get things like
`[Vue warn]: Missing required prop: "dateRange"`
`TypeError: Cannot read property 'startDate' of null`

Would it be much to ask for a working example? With both the html and the **script** for it? I saw the documentation and the html but I just couldn't mach the props to work. 
Thanks a lot!

**Comment by magorizer** [comment]
So i just found the solution in one of the closed issues, and I would really change the documentation to at least show that the main prop is not null?!
![image](https://user-images.githubusercontent.com/47739513/61134096-86e34800-a4c7-11e9-95be-b0c0e2fdd6c1.png)
I got it to work like so
`dateRange: { // used for v-model prop
        startDate:'2019-05-01',
        endDate: '2019-05-15',
      },`
which was not straightforward at all. 
A simple example of what the props look like with the html you put out to your example should help a lot I believe. Thanks

**Comment by nkostadinov** [comment]
thank you for the advice. I will add this to the docs

**Comment by mmusket** [comment]
I concur, 
had to find this issue to set project up. 

Also consider having the bare minimum code available in docs that we can copy and paste for a quick setup.

**Comment by nkostadinov** [comment]
I've taken the note from this issue to update the docs. But i've been really pressured lately at work and cannot find the time to update it. I made major refactor of the docs and guess I've missed some major points. 
FYI: In fact i'm trying to develop self documenting component pattern in this project so this is a side effect of this experiment.

**Comment by mmusket** [comment]
No worries @nkostadinov I only commented as a +1 just so you are aware. All work you put in is appreciated.

**Comment by HamzaAhmad932** [comment]
i appreciate your work 
but
documentation is really weird please update this, 
1- where is the sample code and sample prop data and events. 
2- documentation is not beginners friendly.

**Comment by nguyenquilong** [comment]
Dear, 
My work :

You must import : 

<script>
import moment from "moment";
import DateRangePicker from "vue2-daterange-picker";
import "vue2-daterange-picker/dist/vue2-daterange-picker.css";
...
data() {
   return {
      startDate: "2017-09-05",
      endDate: "2017-09-15",
      dateRange: {
        startDate: "2019-09-01",
        endDate: "2019-09-15"
      },
      locale: {
        direction: "ltr", //direction of text
        format: "DD-MM-YYYY", //fomart of the dates displayed
        separator: " - ", //separator between the two ranges
        applyLabel: "Apply",
        cancelLabel: "Cancel",
        weekLabel: "W",
        customRangeLabel: "Custom Range",
        daysOfWeek: moment.weekdaysMin(), //array of days - see moment documenations for details
        monthNames: moment.monthsShort(), //array of month names - see moment documenations for details
        firstDay: 1 //ISO first day of week - see moment documenations for details
      }
}
}

In <template> 

 <date-range-picker
              v-model="dateRange"
              :startDate="startDate"
              :endDate="endDate"
              :locale-data="locale"
            >
              
              <div slot="input" slot-scope="picker">
                {{ picker.startDate }} - {{ picker.endDate }}
              </div>
            </date-range-picker>

this all. Hope you ok :)

**Comment by nguyenquilong** [comment]
`<date-range-picker
              v-model="dateRange"
              :startDate="startDate"
              :endDate="endDate"
              :locale-data="locale"
            >
              
              <div slot="input" slot-scope="picker">
                {{ picker.startDate }} - {{ picker.endDate }}
              </div>
            </date-range-picker>`

**Comment by nkostadinov** [comment]
I improved the documentation and added some more examples (1 for now but the list will grow). If you see some specific problem please report so I can fix it.
