### ISSUE TITLE
When a max date is set, the Single Date Picker never shows the month containing the max date

### ISSUE THREAD

**Issue by iadcode** [Innologica/vue2-daterange-picker#77]
#### What I did:
* https://innologica.github.io/vue2-daterange-picker/#example-playground
* Check `singleDatePicker`
* Set minDate to `2019-02-15`
* Set maxDate to `2019-04-15`
* Tried to navigate across months using the arrows at the top of the calendar, or by using the dropdowns

#### What I expected:
* To be able to navigate between February, March and April

#### What happened instead:
* I was only able to navigate between February and March

It seems that I can't navigate into a month containing the end date for a Single Date Picker.

#### What I think the problem is:
* In the function below...
https://github.com/Innologica/vue2-daterange-picker/blob/bb9c8291a3f6166058faebde0a324f9457ca1f53/src/components/DateRangePicker.vue#L330-L339
... there is validation to make sure that the date range for the `monthDate` and `nextMonthDate` is not outside of the `min`/`maxDate`s.
* This check will force the `monthDate` back one month if it happens to equal `nextMonthDate`.
* I think this doesn't really make sense/matter in the `singleDatePicker` sense, so perhaps we ought to be checking that this isn't a `singleDatePicker` before moving the `monthDate` backwards?

---

I'll raise PR with a fix described by the line above, in case you're happy with that solution.

**Comment by nkostadinov** [comment]
Added your solution to the source. Will come with next version.
