### ISSUE TITLE
Internet explorer - not working

### ISSUE THREAD

**Issue by bobesiulian** [Innologica/vue2-daterange-picker#79]
the component is not working on Internet Explorer (any version). The app crash at the beginning, but without seeing any bug in ie debugger. Is there any solution to this?
I've tested it in a new empty project and have the same behavior on ie.

**Comment by iadcode** [comment]
Are you able to share how you're using the component?

From what I understand, the component is using some ES6 stuff which IE won't understand, so the solution will involve either just manually including polyfilled ES6 stuff, or using babel to automatically do it for you.

**Comment by bobesiulian** [comment]
ok, i'll take a look at this. thx
