### ISSUE TITLE
Override select style

### ISSUE THREAD

**Issue by JonathanVandal** [Innologica/vue2-daterange-picker#84]
I'm using Vuetify but when I remove `showWeekNumbers` the select input (months and years) overlap. It's caused by Vuetify style because they use : 

```
[type=number] {
    width: auto;
}
```

How can I set `width: 100% !important` to the select `yearselect col` ?

**Comment by nkostadinov** [comment]
You can use a deep selector e.g :

<style lang="scss" scoped>
    .vue-daterange-picker ::v-deep .yearselect {
        .....
    }
</style>
