### ISSUE TITLE
Always make date range picker visible? 

### ISSUE THREAD

**Issue by havietduc91** [Innologica/vue2-daterange-picker#87]
Firstly, congrats for the great effort you've put in vue2-daterangepicker 

Can I set the calendar in a div? to always show, not by click.

Thank you first!

**Comment by nkostadinov** [comment]
thank you ! currently this is not possible. But I'm thinking to allow this in a future release.

The calendar itself is built with a couple of components behind the scenes. Each of these should be separate standalone component - its a WIP but I dont think that will be ready in the next couple of months. 

But I promise to think of a solution for you case :)

**Comment by havietduc91** [comment]
Thank you for a quick response! Hope that we will see a solution soon!

**Comment by josefryzi** [comment]
@havietduc91 I needed the same feature as you, so I created fork and added this feature. If you are interested, pelase see - https://github.com/josefryzi/vue2-daterange-picker/commit/8f70a04dddd479348655736bdcd4ddc6a11910aa

Basically, you just need to add property :inline="true" and it works.
Please let me know if you like it.

**Comment by havietduc91** [comment]
Hi @josefryzi,

Thank you for your help, really glad about that, so I close this issue right away.
