### ISSUE TITLE
Support two ranges in one daterange picker

### ISSUE THREAD

**Issue by havietduc91** [Innologica/vue2-daterange-picker#88]
Firstly, congrats for the great effort you've put in vue2-daterangepicker!

How we can make date range picker with two ranges?
One range for `set time frame` with `yellow color (#FEF2E5)`
and two range for `compare time frame` with `green color (#E9F6FE)`

could you please see the below image to know more!

![Screenshot (43)](https://user-images.githubusercontent.com/4966192/63509865-64513f80-c507-11e9-8bd7-cf5f0dee5ea7.png)

Thank you in advance!

**Comment by nkostadinov** [comment]
Do you mean one of the ranges to be preselected ?

**Comment by havietduc91** [comment]
I mean, there are two range pickers showed in one calendar with `timeFrameStartDate`, `timeFrameEndDate`, `compareTimeFrameStartDate`, `compareTimeFrameEndDate`. And we can select range for `timeFrame` and `compareTimeFrame`, like the below image 

![Screenshot (44)](https://user-images.githubusercontent.com/4966192/63562582-5b548280-c588-11e9-81fa-85e91ccc4d6a.png)

**Comment by Namnd-gem** [comment]
I am facing that issue too. I need to have 2 different preselected time ranges and it's on same date picker component. Could you advise how could we do it? @nkostadinov

**Comment by nkostadinov** [comment]
There is a way to do it but you have to implement the range selector and put it in the slot. 

Then there is a prop date-format which is a callback function called for every date rendered. In this function you have to add logic to color the corresponding dates if they are in the selected ranges.

**Comment by havietduc91** [comment]
I see your point, but I resolved it in-house.

Thank @nkostadinov for your response! So I will close this issue right away!
