### ISSUE TITLE
Incorrect date-range when selecting two pre-dating dates in the row

### ISSUE THREAD

**Issue by danielHalan** [Innologica/vue2-daterange-picker#9]
1. Open selector
2. Click a valid range, i.e. 2018-09-01 => 2018-09-20
3. Now Click on 2018-09-08 and then 2018-09-01, this results in range 2018-09-08 => 2018-09-01

Expected behavior, when click on a date "pre-dating" the selected date, make that date the new "start-date".

**Comment by nkostadinov** [comment]
I made the component behave like the original. If you select end date less than the start date, then the value becomes the new start date and you continue to select the end date.
