### ISSUE TITLE
Feature Request: Ability to add "all" dates for ranges

### ISSUE THREAD

**Issue by D-Marc1** [Innologica/vue2-daterange-picker#91]
Essentially, this would select nothing. In the current implementation, I don't see how this is possible, even with the ranges slot.

**Comment by D-Marc1** [comment]
Ok, here's a solution for anyone who comes across this and is interested. You'll want to use the ranges slot. I copied the div and `.range` class from the original html it has, as using this slot *replaces* the html. I then traversed the ranges. I'll explain the `@click` methods next.

```
<template v-slot:ranges="{ startDate, endDate, ranges }">
  <div class="ranges col-12 col-md-auto">
    <ul>
      <li
        v-for="(value, name, index) in ranges"
        :key="index"
        @click="setDateRanges(value)"
      >
        {{ name }}
      </li>
      <li @click="setDateRangeAll">All</li>
    </ul>
  </div>
</template>
```

I had no issues setting the start and end dates. The issue was that couldn't find anything in the docs that would allow me to close the date popup. I ended up looking through the repo and directly calling two different methods, via using `refs`. I named mine `dateRangePicker`.

```
setDateRanges(value) {
  this.$refs.dateRangePicker.clickRange(value); //Set date values and close popup
},
setDateRangeAll() {
  //Set dates to empty string for "all"
  this.values.startDate = ''; 
  this.values.endDate = '';

  this.$refs.dateRangePicker.togglePicker(false, true); //Just close the popup
},
```

I hope this helps someone.

**Comment by nkostadinov** [comment]
Can you elaborate a little on this issue ? What do you mean by "select all" in the ranges, do you mean a button to clear the dates or something else ?

**Comment by D-Marc1** [comment]
I suppose it could technically be either. I'm not sure how selecting all would work, unless it just selects an insanely old 
start date and absurdly high end date. I ended up making it select nothing.

**Comment by nkostadinov** [comment]
Yes, you could easily clear the selection when you set both dates to null.
