### ISSUE TITLE
Tutorial or Sample Code

### ISSUE THREAD

**Issue by rexdarel** [Innologica/vue2-daterange-picker#92]
Hi, I am trying to add this on my project. Laravel with Vue. It is perfect for hotel booking. I tried to add it on my project but the input field is not clickable. 

![image](https://user-images.githubusercontent.com/30248326/65430199-1dc66c00-de4a-11e9-8a04-6fe142d0b2b4.png)

```
<template>
    <div class="form-group">
        <label class="form-control-label" :for="name">{{label}}</label>
        <date-range-picker
                :opens="opens"
                @update="console.log(value)"
                :locale-data="locale"
                v-model="dateRange"
        >
            <!--Optional scope for the input displaying the dates -->
            <div slot="input" slot-scope="picker">
                {{ picker.startDate | date }} - {{ picker.endDate | date }}
            </div>
        </date-range-picker>
    </div>
</template>
<script>
    import moment from 'moment'
    import DateRangePicker from 'vue2-daterange-picker'
    

    export default {
        components: {DateRangePicker},
        name: 'picker',
        props: ['name', 'label'],
        filters: {
            date (value) {
                let options = {year: 'numeric', month: 'long', day: 'numeric'};
                return Intl.DateTimeFormat('en-US', options).format(value)
            }
        },
        data() {
            return {
                opens: 'center',
                dateRange: {
                    startDate: '2017-09-05',
                    endDate: '2019-09-15',
                },
                startDate: '2017-09-05',
                endDate: '2019-09-15',
                locale: {
                    direction: 'ltr', //direction of text
                    format: 'DD-MM-YYYY', //fomart of the dates displayed
                    separator: ' - ', //separator between the two ranges
                    applyLabel: 'Apply',
                    cancelLabel: 'Cancel',
                    weekLabel: 'W',
                    customRangeLabel: 'Custom Range',
                    daysOfWeek: moment.weekdaysMin(), //array of days - see moment documenations for details
                    monthNames: moment.monthsShort(), //array of month names - see moment documenations for details
                    firstDay: 1 //ISO first day of week - see moment documenations for details
                }
            }
        },
    }
</script>
```

**Comment by rexdarel** [comment]
I've read here that you need to import vue2-daterange-picker/dist/lib/vue-daterange-picker.min.css . I don't know how to import css files in laravel-vue

**Comment by rexdarel** [comment]
I was able to work the css problem. But when clicking the input field the calendar doesnt show up. If I inspect element it, and clicking the input field, there is an html for dropdown (calendar), it will show or hide when clicking the input field. but it will not show in the browser 

![image](https://user-images.githubusercontent.com/30248326/65433553-d6db7500-de4f-11e9-9e83-0d5dc713863d.png)

**Comment by rexdarel** [comment]
The dropdown was set to `display:none` , when disabling it, the dropdown will show but with ugly layout.
![image](https://user-images.githubusercontent.com/30248326/65433722-1d30d400-de50-11e9-9bd4-7ebd2c58310b.png)

**Comment by rexdarel** [comment]
![image](https://user-images.githubusercontent.com/30248326/65433813-4fdacc80-de50-11e9-8241-d5cd03799f1d.png)

**Comment by nkostadinov** [comment]
you are missing the CSS. Can you try to include it like this and see if that works for you :

`import 'vue2-daterange-picker/dist/vue2-daterange-picker.css'`
