### ISSUE TITLE
Changing time does not update model

### ISSUE THREAD

**Issue by pgross** [Innologica/vue2-daterange-picker#95]
When using the time picker, if you select a time for either the start or end of the date range, I would expect the model to be updated with that new time.  Currently it does not always update the time portion of the date range.

If you change the time in the example playground, it will not save the time if you click Apply.  It will not save the time if you change it and click off the popup.

The time is only saved if the user selects a time from the time picker and then selects a date range after that.

**Comment by nkostadinov** [comment]
hmm, I will check that. time was added later so it may have some issues

**Comment by nkostadinov** [comment]
This should be fixed in ver 0.4 i just released.
