### ISSUE TITLE
The component scales incorrectly when the scale is 110%

### ISSUE THREAD

**Issue by k2042** [Innologica/vue2-daterange-picker#97]
Hello.

The component scales wrong in Chrome at 110%, both at 768 and 540 scaled screen width. It looks like this: https://imgur.com/a/hSBKZET Can be observed right on the demo page: https://innologica.github.io/vue2-daterange-picker

It can be fixed by setting slightly larger min-widths (like +10px more), the downside is that it introduces some excess margin on the right side. Like this:

```
@media (min-width: 540px) {
    .daterangepicker.show-ranges {
        min-width: 496px !important;
    }
}

@media (min-width: 768px) {
    .daterangepicker.show-ranges {
         min-width: 640px !important;
     }
 }
```

!important was needed because the styles responsible are scoped inside the vue-files of the component.

**Comment by KatreMetsvahi** [comment]
Same problem exists in Firefox when zoom is less than 100%.

**Comment by nkostadinov** [comment]
fixed in the current version
