### ISSUE TITLE
Consider replacing moment.js (webpack case)?

### ISSUE THREAD

**Issue by it-xtech-dev** [Innologica/vue2-daterange-picker#99]
Hello,

I have bundled this component with webpack and was supprised to see that it is about 300k minified (thats a bit large as for the single purpose component). Searched for a reason an here it is (moment.js + locales) - all locales are loaded into bundle even when not used.

<img src="https://i.imgur.com/GJbrq3W.png">

As you can see moment.js is quite huge compared with component native code.

Further search leads to this solutions:
https://github.com/jmblog/how-to-optimize-momentjs-with-webpack
https://github.com/you-dont-need/You-Dont-Need-Momentjs
https://github.com/ksloan/moment-mini

So here's my question: Can you consider replacing moment.js with proper alternative that will not produce so large webpack bundles?

Best Regards,
It-Man

**Comment by nkostadinov** [comment]
Yes, I'm considering switching to date-fns because I also dont like the bundle size and mutability of moment.js objects. It's in the roadmap but I don't when will have time to do that.

**Comment by nkostadinov** [comment]
I havent used dayjs yet. I'm using date-fns in another project and it works pretty well, that's why I was considering it.

**Comment by it-xtech-dev** [comment]
How about api compatibility between date-fns and moment? dayjs is quite similar so it is easier to migrate. Did you considered this aspect?

**Comment by nkostadinov** [comment]
I'm thinking of a proxy object which can be passed via configuration props (like locale) with a couple of functions that I need so anyone can implement their own date functions.

**Comment by it-xtech-dev** [comment]
Sounds interesting but it seems it prevents out of the box usage? Or do plan to provide some default configuration / implementation?

**Comment by nkostadinov** [comment]
default implementation should be mapped directly to the lib that I choose e.g. date-fns, moment or dayjs. And if you dont like it you need to provide an object with the same methods which should wrap whatever logic (or lib) you want inside.

**Comment by it-xtech-dev** [comment]
Sounds interesting I'm curious about the implementation. It looks like provided library should have same api as the one you choose as preferred. That might force developers to write additional code just to have an api compatible with this single component.

Any how do you plan to pass lib reference? Over component property?

**Comment by nkostadinov** [comment]
It's still only in my head but should be something like:

```
myLib = {
  today() {...  moment.today()  }
  formatDate () {... date-fns.format() }
.....
}
<date-range-picker :date-lib=myLib  />
```

I could even make wrappers for the 2 most used libs to ease on the users ... but I'm still considering this. It may be too much work and these libs change constantly.

**Comment by it-xtech-dev** [comment]
Do you think that pass reference as property will not degrade performance or interfere the lib? Props ad wrapped with observers so as far as i know original object will be modified.

**Comment by nkostadinov** [comment]
I dont think that degrading performance will be an issue. But may be modification of object will be, I need to test it well.

**Comment by it-xtech-dev** [comment]
Ok.

For your note: here is fork with moment -> dayjs:
https://github.com/it-xtech-dev/vue2-daterange-picker

It-Man

**Comment by nkostadinov** [comment]
I implemented all functions with native date object. Also added implentations with date-fns, moment and ability to create custom object.
